import type { PortalAccount } from '../types';
import { SALES_REPS } from './sales-reps';

export const PORTAL_ACCOUNTS: PortalAccount[] = [
  // ─── Greenfield Dispensary (Seattle) ───────────────────────────
  {
    id: 'acct-1',
    businessName: 'Greenfield Dispensary',
    dba: 'Greenfield Cannabis',
    licenseNumber: 'WSLCB-GF-001',
    address: {
      street: '4521 Aurora Ave N',
      city: 'Seattle',
      state: 'WA',
      zip: '98103',
    },
    deliveryAddress: {
      street: '4521 Aurora Ave N',
      city: 'Seattle',
      state: 'WA',
      zip: '98103',
    },
    primaryContact: {
      id: 'contact-1',
      name: 'Sarah Chen',
      role: 'buyer',
      email: 'sarah@greenfielddispensary.com',
      phone: '(206) 555-0134',
      hasPortalAccess: true,
      isPrimary: true,
    },
    contacts: [
      {
        id: 'contact-1',
        name: 'Sarah Chen',
        role: 'buyer',
        email: 'sarah@greenfielddispensary.com',
        phone: '(206) 555-0134',
        hasPortalAccess: true,
        isPrimary: true,
      },
      {
        id: 'contact-2',
        name: 'Mike Torres',
        role: 'manager',
        email: 'mike@greenfielddispensary.com',
        phone: '(206) 555-0156',
        hasPortalAccess: true,
        isPrimary: false,
      },
      {
        id: 'contact-3',
        name: 'Lisa Park',
        role: 'budtender',
        email: 'lisa@greenfielddispensary.com',
        phone: '(206) 555-0178',
        hasPortalAccess: false,
        isPrimary: false,
      },
    ],
    assignedRep: SALES_REPS[0],
    healthScore: 92,
    healthStatus: 'thriving',
    pipelineStatus: 'A4',
    pipelineLabel: 'Premium',
    vmiEnrolled: true,
    pricingTier: 1,
    preferredDeliveryWindow: {
      days: ['Mon', 'Wed', 'Fri'],
      timeStart: '8:00 AM',
      timeEnd: '12:00 PM',
    },
    lifetimeRevenue: 380000,
    outstandingBalance: 0,
    lastOrderDate: '2026-03-06',
    accountSince: '2025-06-15',
    notificationPreferences: {
      orderUpdates: true,
      deliveryAlerts: true,
      newProducts: true,
      promotions: true,
      paymentReminders: true,
      stockAlerts: true,
      method: 'both',
    },
    savedTemplates: [
      {
        id: 'tmpl-1',
        name: 'Weekly Restock',
        items: [
          { productId: 'prod-fl-wc-35', quantity: 12 },
          { productId: 'prod-fl-bd-35', quantity: 10 },
          { productId: 'prod-pr-wc-3pk', quantity: 8 },
          { productId: 'prod-ed-gum-10', quantity: 6 },
        ],
        createdAt: '2025-09-10',
        lastUsed: '2026-03-04',
        estimatedTotal: 2400,
      },
      {
        id: 'tmpl-2',
        name: 'Premium Flower',
        items: [
          { productId: 'prod-fl-wc-35', quantity: 10 },
          { productId: 'prod-fl-gel-35', quantity: 8 },
          { productId: 'prod-fl-og-35', quantity: 8 },
        ],
        createdAt: '2025-10-22',
        lastUsed: '2026-02-28',
        estimatedTotal: 1800,
      },
      {
        id: 'tmpl-3',
        name: 'Weekend Rush',
        items: [
          { productId: 'prod-pr-bd-3pk', quantity: 10 },
          { productId: 'prod-ed-gum-10', quantity: 8 },
          { productId: 'prod-bev-selt-10', quantity: 6 },
        ],
        createdAt: '2025-11-05',
        lastUsed: '2026-03-01',
        estimatedTotal: 950,
      },
    ],
    unreadNotifications: 6,
    unreadMessages: 2,
    storeOrdersEnabled: true,
    autoAcceptOrders: false,
    connectedIntegrations: [
      {
        id: 'int-1',
        platform: 'dutchie',
        status: 'connected',
        connectedAt: '2025-09-01',
        lastSyncAt: '2026-03-08',
        label: 'Dutchie',
        description: 'Online ordering and menu management',
        logoIcon: 'ShoppingCart',
      },
      {
        id: 'int-2',
        platform: 'jane',
        status: 'connected',
        connectedAt: '2025-11-15',
        lastSyncAt: '2026-03-08',
        label: 'Jane Technologies',
        description: 'Real-time menu sync and ordering',
        logoIcon: 'Store',
      },
    ],
  },

  // ─── Pacific Leaf (Tacoma) ─────────────────────────────────────
  {
    id: 'acct-2',
    businessName: 'Pacific Leaf',
    dba: 'Pacific Leaf Cannabis Co',
    licenseNumber: 'WSLCB-PL-002',
    address: {
      street: '1892 Pacific Ave',
      city: 'Tacoma',
      state: 'WA',
      zip: '98402',
    },
    primaryContact: {
      id: 'contact-4',
      name: 'James Park',
      role: 'owner',
      email: 'james@pacificleaf.com',
      phone: '(253) 555-0198',
      hasPortalAccess: true,
      isPrimary: true,
    },
    contacts: [
      {
        id: 'contact-4',
        name: 'James Park',
        role: 'owner',
        email: 'james@pacificleaf.com',
        phone: '(253) 555-0198',
        hasPortalAccess: true,
        isPrimary: true,
      },
      {
        id: 'contact-5',
        name: 'Amy Nguyen',
        role: 'buyer',
        email: 'amy@pacificleaf.com',
        phone: '(253) 555-0211',
        hasPortalAccess: true,
        isPrimary: false,
      },
    ],
    assignedRep: SALES_REPS[1],
    healthScore: 45,
    healthStatus: 'at-risk',
    pipelineStatus: 'A2',
    pipelineLabel: 'Established',
    vmiEnrolled: true,
    pricingTier: 2,
    preferredDeliveryWindow: {
      days: ['Tue', 'Thu'],
      timeStart: '10:00 AM',
      timeEnd: '2:00 PM',
    },
    lifetimeRevenue: 145000,
    outstandingBalance: 4200,
    lastOrderDate: '2026-02-28',
    accountSince: '2025-08-20',
    notificationPreferences: {
      orderUpdates: true,
      deliveryAlerts: true,
      newProducts: true,
      promotions: true,
      paymentReminders: true,
      stockAlerts: false,
      method: 'email',
    },
    savedTemplates: [
      {
        id: 'tmpl-4',
        name: 'Standard Order',
        items: [
          { productId: 'prod-fl-bd-35', quantity: 8 },
          { productId: 'prod-pr-bd-3pk', quantity: 6 },
          { productId: 'prod-vap-bd-10', quantity: 4 },
        ],
        createdAt: '2025-10-01',
        lastUsed: '2026-02-20',
        estimatedTotal: 1100,
      },
      {
        id: 'tmpl-5',
        name: 'Edibles Focus',
        items: [
          { productId: 'prod-ed-gum-10', quantity: 10 },
          { productId: 'prod-ed-gum-25', quantity: 6 },
          { productId: 'prod-ed-choc-10', quantity: 4 },
        ],
        createdAt: '2025-12-15',
        lastUsed: '2026-02-10',
        estimatedTotal: 680,
      },
    ],
    unreadNotifications: 4,
    unreadMessages: 1,
    storeOrdersEnabled: true,
    autoAcceptOrders: false,
    connectedIntegrations: [],
  },

  // ─── Cascade Wellness (Spokane) ────────────────────────────────
  {
    id: 'acct-3',
    businessName: 'Cascade Wellness',
    dba: 'Cascade Wellness Dispensary',
    licenseNumber: 'WSLCB-CW-003',
    address: {
      street: '723 W Main Ave',
      city: 'Spokane',
      state: 'WA',
      zip: '99201',
    },
    primaryContact: {
      id: 'contact-6',
      name: 'Alex Rivera',
      role: 'buyer',
      email: 'alex@cascadewellness.com',
      phone: '(509) 555-0342',
      hasPortalAccess: true,
      isPrimary: true,
    },
    contacts: [
      {
        id: 'contact-6',
        name: 'Alex Rivera',
        role: 'buyer',
        email: 'alex@cascadewellness.com',
        phone: '(509) 555-0342',
        hasPortalAccess: true,
        isPrimary: true,
      },
    ],
    assignedRep: SALES_REPS[0],
    healthScore: 68,
    healthStatus: 'healthy',
    pipelineStatus: 'I5',
    pipelineLabel: 'Converting',
    vmiEnrolled: false,
    pricingTier: 3,
    preferredDeliveryWindow: {
      days: ['Wed'],
      timeStart: '9:00 AM',
      timeEnd: '5:00 PM',
    },
    lifetimeRevenue: 18000,
    outstandingBalance: 0,
    lastOrderDate: '2026-03-01',
    accountSince: '2026-01-10',
    notificationPreferences: {
      orderUpdates: true,
      deliveryAlerts: true,
      newProducts: false,
      promotions: false,
      paymentReminders: true,
      stockAlerts: false,
      method: 'sms',
    },
    savedTemplates: [
      {
        id: 'tmpl-6',
        name: 'First Restock',
        items: [
          { productId: 'prod-fl-bd-35', quantity: 6 },
          { productId: 'prod-pr-wc-single', quantity: 10 },
          { productId: 'prod-ed-gum-10', quantity: 4 },
        ],
        createdAt: '2026-02-01',
        lastUsed: '2026-02-28',
        estimatedTotal: 520,
      },
    ],
    unreadNotifications: 2,
    unreadMessages: 0,
    storeOrdersEnabled: true,
    autoAcceptOrders: true,
    connectedIntegrations: [],
  },
];

export function getAccountById(id: string): PortalAccount | undefined {
  return PORTAL_ACCOUNTS.find((account) => account.id === id);
}
