import type { PortalCOA } from '../types';

export const PORTAL_COAS: PortalCOA[] = [
  {
    id: 'coa-001',
    batchNumber: 'BATCH-2026-1001',
    productName: 'Wedding Cake 3.5g',
    category: 'flower',
    testDate: '2026-02-28',
    lab: 'Confidence Analytics',
    thcResult: 27.3,
    cbdResult: 0.08,
    terpenes: [
      { name: 'Limonene', percentage: 1.82 },
      { name: 'Caryophyllene', percentage: 1.45 },
      { name: 'Linalool', percentage: 0.67 },
      { name: 'Myrcene', percentage: 0.52 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1001.pdf',
  },
  {
    id: 'coa-002',
    batchNumber: 'BATCH-2026-1002',
    productName: 'Wedding Cake 7g',
    category: 'flower',
    testDate: '2026-02-28',
    lab: 'Confidence Analytics',
    thcResult: 27.1,
    cbdResult: 0.09,
    terpenes: [
      { name: 'Limonene', percentage: 1.78 },
      { name: 'Caryophyllene', percentage: 1.40 },
      { name: 'Linalool', percentage: 0.62 },
      { name: 'Myrcene', percentage: 0.48 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1002.pdf',
  },
  {
    id: 'coa-003',
    batchNumber: 'BATCH-2026-1003',
    productName: 'Blue Dream 3.5g',
    category: 'flower',
    testDate: '2026-02-25',
    lab: 'Green Leaf Lab',
    thcResult: 21.6,
    cbdResult: 0.12,
    terpenes: [
      { name: 'Myrcene', percentage: 2.10 },
      { name: 'Pinene', percentage: 0.95 },
      { name: 'Caryophyllene', percentage: 0.68 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1003.pdf',
  },
  {
    id: 'coa-004',
    batchNumber: 'BATCH-2026-1004',
    productName: 'Blue Dream 7g',
    category: 'flower',
    testDate: '2026-02-25',
    lab: 'Green Leaf Lab',
    thcResult: 21.8,
    cbdResult: 0.11,
    terpenes: [
      { name: 'Myrcene', percentage: 2.15 },
      { name: 'Pinene', percentage: 0.90 },
      { name: 'Caryophyllene', percentage: 0.72 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1004.pdf',
  },
  {
    id: 'coa-005',
    batchNumber: 'BATCH-2026-1005',
    productName: 'Gelato 3.5g',
    category: 'flower',
    testDate: '2026-03-01',
    lab: 'Confidence Analytics',
    thcResult: 28.4,
    cbdResult: 0.06,
    terpenes: [
      { name: 'Myrcene', percentage: 1.65 },
      { name: 'Limonene', percentage: 1.42 },
      { name: 'Caryophyllene', percentage: 0.88 },
      { name: 'Linalool', percentage: 0.45 },
      { name: 'Humulene', percentage: 0.32 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1005.pdf',
  },
  {
    id: 'coa-006',
    batchNumber: 'BATCH-2026-1006',
    productName: 'Zkittlez 3.5g',
    category: 'flower',
    testDate: '2026-02-20',
    lab: 'Green Leaf Lab',
    thcResult: 23.7,
    cbdResult: 0.10,
    terpenes: [
      { name: 'Caryophyllene', percentage: 1.30 },
      { name: 'Linalool', percentage: 0.98 },
      { name: 'Humulene', percentage: 0.55 },
      { name: 'Myrcene', percentage: 0.42 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1006.pdf',
  },
  {
    id: 'coa-007',
    batchNumber: 'BATCH-2026-1007',
    productName: 'OG Kush 3.5g',
    category: 'flower',
    testDate: '2026-02-18',
    lab: 'Confidence Analytics',
    thcResult: 24.2,
    cbdResult: 0.05,
    terpenes: [
      { name: 'Myrcene', percentage: 1.95 },
      { name: 'Limonene', percentage: 1.10 },
      { name: 'Caryophyllene', percentage: 0.78 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1007.pdf',
  },
  {
    id: 'coa-008',
    batchNumber: 'BATCH-2026-1008',
    productName: 'OG Kush 7g',
    category: 'flower',
    testDate: '2026-02-18',
    lab: 'Confidence Analytics',
    thcResult: 24.0,
    cbdResult: 0.06,
    terpenes: [
      { name: 'Myrcene', percentage: 1.88 },
      { name: 'Limonene', percentage: 1.05 },
      { name: 'Caryophyllene', percentage: 0.82 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1008.pdf',
  },
  {
    id: 'coa-009',
    batchNumber: 'BATCH-2026-1009',
    productName: 'Mimosa 3.5g',
    category: 'flower',
    testDate: '2026-02-15',
    lab: 'Green Leaf Lab',
    thcResult: 22.5,
    cbdResult: 0.14,
    terpenes: [
      { name: 'Limonene', percentage: 2.40 },
      { name: 'Myrcene', percentage: 0.85 },
      { name: 'Pinene', percentage: 0.60 },
      { name: 'Terpinolene', percentage: 0.38 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1009.pdf',
  },
  {
    id: 'coa-010',
    batchNumber: 'BATCH-2026-1010',
    productName: 'Wedding Cake Preroll 5-Pack',
    category: 'prerolls',
    testDate: '2026-03-02',
    lab: 'Confidence Analytics',
    thcResult: 26.8,
    cbdResult: 0.07,
    terpenes: [
      { name: 'Limonene', percentage: 1.75 },
      { name: 'Caryophyllene', percentage: 1.38 },
      { name: 'Linalool', percentage: 0.58 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1010.pdf',
  },
  {
    id: 'coa-011',
    batchNumber: 'BATCH-2026-1011',
    productName: 'Blue Dream Preroll 5-Pack',
    category: 'prerolls',
    testDate: '2026-02-22',
    lab: 'Green Leaf Lab',
    thcResult: 20.9,
    cbdResult: 0.15,
    terpenes: [
      { name: 'Myrcene', percentage: 2.05 },
      { name: 'Pinene', percentage: 0.88 },
      { name: 'Caryophyllene', percentage: 0.62 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1011.pdf',
  },
  {
    id: 'coa-012',
    batchNumber: 'BATCH-2026-1012',
    productName: 'Gelato Live Resin Cart 1g',
    category: 'vaporizers',
    testDate: '2026-03-03',
    lab: 'Confidence Analytics',
    thcResult: 85.2,
    cbdResult: 0.30,
    terpenes: [
      { name: 'Myrcene', percentage: 2.25 },
      { name: 'Limonene', percentage: 1.80 },
      { name: 'Caryophyllene', percentage: 1.10 },
      { name: 'Linalool', percentage: 0.55 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1012.pdf',
  },
  {
    id: 'coa-013',
    batchNumber: 'BATCH-2026-1013',
    productName: 'Blue Dream Cart 1g',
    category: 'vaporizers',
    testDate: '2026-02-20',
    lab: 'Green Leaf Lab',
    thcResult: 82.7,
    cbdResult: 0.45,
    terpenes: [
      { name: 'Myrcene', percentage: 2.50 },
      { name: 'Pinene', percentage: 1.15 },
      { name: 'Caryophyllene', percentage: 0.70 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1013.pdf',
  },
  {
    id: 'coa-014',
    batchNumber: 'BATCH-2026-1014',
    productName: 'OG Kush Cart 0.5g',
    category: 'vaporizers',
    testDate: '2026-02-17',
    lab: 'Confidence Analytics',
    thcResult: 84.1,
    cbdResult: 0.20,
    terpenes: [
      { name: 'Myrcene', percentage: 2.30 },
      { name: 'Limonene', percentage: 1.25 },
      { name: 'Caryophyllene', percentage: 0.90 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1014.pdf',
  },
  {
    id: 'coa-015',
    batchNumber: 'BATCH-2026-1015',
    productName: 'Zkittlez Live Resin 1g',
    category: 'concentrates',
    testDate: '2026-03-04',
    lab: 'Confidence Analytics',
    thcResult: 78.5,
    cbdResult: 0.18,
    terpenes: [
      { name: 'Caryophyllene', percentage: 1.85 },
      { name: 'Linalool', percentage: 1.42 },
      { name: 'Humulene', percentage: 0.75 },
      { name: 'Myrcene', percentage: 0.60 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1015.pdf',
  },
  {
    id: 'coa-016',
    batchNumber: 'BATCH-2026-1016',
    productName: 'Wedding Cake Badder 1g',
    category: 'concentrates',
    testDate: '2026-02-26',
    lab: 'Green Leaf Lab',
    thcResult: 76.8,
    cbdResult: 0.12,
    terpenes: [
      { name: 'Limonene', percentage: 2.10 },
      { name: 'Caryophyllene', percentage: 1.55 },
      { name: 'Linalool', percentage: 0.72 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1016.pdf',
  },
  {
    id: 'coa-017',
    batchNumber: 'BATCH-2026-1017',
    productName: 'Gelato Live Resin 1g',
    category: 'concentrates',
    testDate: '2026-03-05',
    lab: 'Confidence Analytics',
    thcResult: 80.2,
    cbdResult: 0.15,
    terpenes: [
      { name: 'Myrcene', percentage: 2.00 },
      { name: 'Limonene', percentage: 1.65 },
      { name: 'Caryophyllene', percentage: 1.02 },
      { name: 'Linalool', percentage: 0.48 },
      { name: 'Humulene', percentage: 0.30 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1017.pdf',
  },
  {
    id: 'coa-018',
    batchNumber: 'BATCH-2026-1018',
    productName: 'Frost Gummies Watermelon 10-Pack',
    category: 'edibles',
    testDate: '2026-02-12',
    lab: 'Green Leaf Lab',
    thcResult: 10.2,
    cbdResult: 0.50,
    terpenes: [
      { name: 'Myrcene', percentage: 0.15 },
      { name: 'Limonene', percentage: 0.10 },
      { name: 'Linalool', percentage: 0.08 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1018.pdf',
  },
  {
    id: 'coa-019',
    batchNumber: 'BATCH-2026-1019',
    productName: 'Frost Gummies Mango 10-Pack',
    category: 'edibles',
    testDate: '2026-02-12',
    lab: 'Green Leaf Lab',
    thcResult: 10.1,
    cbdResult: 0.48,
    terpenes: [
      { name: 'Myrcene', percentage: 0.18 },
      { name: 'Limonene', percentage: 0.12 },
      { name: 'Terpinolene', percentage: 0.10 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1019.pdf',
  },
  {
    id: 'coa-020',
    batchNumber: 'BATCH-2026-1020',
    productName: 'Frost Sparkling Water Lemon 5mg',
    category: 'beverages',
    testDate: '2026-02-10',
    lab: 'Confidence Analytics',
    thcResult: 5.1,
    cbdResult: 0.25,
    terpenes: [
      { name: 'Limonene', percentage: 0.22 },
      { name: 'Pinene', percentage: 0.10 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1020.pdf',
  },
  {
    id: 'coa-021',
    batchNumber: 'BATCH-2026-1021',
    productName: 'Frost Sparkling Water Berry 10mg',
    category: 'beverages',
    testDate: '2026-02-10',
    lab: 'Confidence Analytics',
    thcResult: 10.3,
    cbdResult: 0.30,
    terpenes: [
      { name: 'Myrcene', percentage: 0.18 },
      { name: 'Linalool', percentage: 0.12 },
    ],
    passStatus: 'pass',
    downloadUrl: '/coas/BATCH-2026-1021.pdf',
  },
  {
    id: 'coa-022',
    batchNumber: 'BATCH-2026-1022',
    productName: 'Mimosa Preroll 5-Pack',
    category: 'prerolls',
    testDate: '2026-01-28',
    lab: 'Green Leaf Lab',
    thcResult: 0.0,
    cbdResult: 0.0,
    terpenes: [],
    passStatus: 'fail',
    downloadUrl: '/coas/BATCH-2026-1022.pdf',
  },
];

export function getCoasForProduct(productName: string): PortalCOA[] {
  const normalized = productName.toLowerCase();
  return PORTAL_COAS.filter(
    (coa) => coa.productName.toLowerCase().includes(normalized) && coa.passStatus === 'pass'
  );
}
