import type { PortalNotification } from '../types';

const GREENFIELD_NOTIFICATIONS: PortalNotification[] = [
  {
    id: 'notif-g-001',
    type: 'store_order',
    title: 'New Pickup Order',
    body: 'New pickup order from Dutchie — Maria L. ordered Blue Dream 3.5g and Wedding Cake prerolls.',
    timestamp: '2026-03-08T14:22:00Z',
    read: false,
    actionUrl: '/portal/store-orders/SO-1001',
    actionLabel: 'View order',
    icon: 'ShoppingBag',
    severity: 'info',
  },
  {
    id: 'notif-g-002',
    type: 'delivery_alert',
    title: 'Driver En Route',
    body: 'Driver en route — ETA 25 min. Your order ORD-2026-0845 is on its way.',
    timestamp: '2026-03-08T11:45:00Z',
    read: false,
    actionUrl: '/portal/deliveries/del-101',
    actionLabel: 'Track delivery',
    icon: 'Truck',
    severity: 'info',
  },
  {
    id: 'notif-g-003',
    type: 'ai_suggestion',
    title: 'Reorder Suggestion',
    body: 'Reorder suggestion: your Wedding Cake stock is running low. Based on your sales velocity, you\'ll run out in ~3 days.',
    timestamp: '2026-03-08T09:30:00Z',
    read: false,
    actionUrl: '/portal/ai-assistant',
    actionLabel: 'Review suggestion',
    icon: 'Sparkles',
    severity: 'info',
  },
  {
    id: 'notif-g-004',
    type: 'store_order',
    title: 'Orders Waiting for Pickup',
    body: '3 orders waiting for pickup. Oldest order placed 45 minutes ago — check your prep queue.',
    timestamp: '2026-03-08T08:15:00Z',
    read: false,
    actionUrl: '/portal/store-orders',
    actionLabel: 'View queue',
    icon: 'ShoppingBag',
    severity: 'warning',
  },
  {
    id: 'notif-g-005',
    type: 'new_product',
    title: 'New Gelato Line Available',
    body: 'New Gelato line now available — 3.5g flower, 1g carts, and live resin concentrate. Check the catalog for pricing.',
    timestamp: '2026-03-07T16:00:00Z',
    read: false,
    actionUrl: '/portal/catalog?filter=gelato',
    actionLabel: 'View products',
    icon: 'PackagePlus',
    severity: 'info',
  },
  {
    id: 'notif-g-006',
    type: 'order_update',
    title: 'Order Confirmed',
    body: 'ORD-2026-0845 confirmed. Your order of 24 units is being prepared for fulfillment.',
    timestamp: '2026-03-07T14:30:00Z',
    read: false,
    actionUrl: '/portal/orders/ORD-2026-0845',
    actionLabel: 'View order',
    icon: 'ClipboardCheck',
    severity: 'info',
  },
  {
    id: 'notif-g-007',
    type: 'promotion',
    title: 'Concentrate Week — 10% Off',
    body: 'Concentrate Week — 10% off all concentrates through March 14. Stock up on live resin and badder.',
    timestamp: '2026-03-07T10:00:00Z',
    read: true,
    actionUrl: '/portal/catalog?category=concentrates',
    actionLabel: 'Shop concentrates',
    icon: 'Tag',
    severity: 'info',
  },
  {
    id: 'notif-g-008',
    type: 'order_update',
    title: 'Order Shipped',
    body: 'ORD-2026-0843 shipped. Expected delivery on March 10 between 10 AM and 2 PM.',
    timestamp: '2026-03-06T17:00:00Z',
    read: true,
    actionUrl: '/portal/orders/ORD-2026-0843',
    actionLabel: 'Track shipment',
    icon: 'ClipboardCheck',
    severity: 'info',
  },
  {
    id: 'notif-g-009',
    type: 'delivery_alert',
    title: 'Delivery Scheduled',
    body: 'Delivery scheduled for Mar 10. Your Tuesday delivery window (10 AM – 2 PM) is confirmed.',
    timestamp: '2026-03-06T15:00:00Z',
    read: true,
    actionUrl: '/portal/deliveries/del-101',
    actionLabel: 'View details',
    icon: 'CalendarCheck',
    severity: 'info',
  },
  {
    id: 'notif-g-010',
    type: 'store_order',
    title: 'Pickup Order Completed',
    body: 'Pickup order completed — Tyler R. picked up his order of Zkittlez prerolls and a Gelato cart.',
    timestamp: '2026-03-06T13:20:00Z',
    read: true,
    actionUrl: '/portal/store-orders/SO-0998',
    actionLabel: 'View order',
    icon: 'ShoppingBag',
    severity: 'info',
  },
  {
    id: 'notif-g-011',
    type: 'new_product',
    title: 'Zkittlez Concentrates In Stock',
    body: 'Zkittlez concentrates in stock — live resin and badder now available in 1g jars.',
    timestamp: '2026-03-06T09:00:00Z',
    read: true,
    actionUrl: '/portal/catalog?filter=zkittlez',
    actionLabel: 'View products',
    icon: 'PackagePlus',
    severity: 'info',
  },
  {
    id: 'notif-g-012',
    type: 'promotion',
    title: 'Wedding Cake Bundle Deal',
    body: 'Wedding Cake Bundle deal — buy 12+ Wedding Cake 3.5g and get 15% off. Limited time offer.',
    timestamp: '2026-03-05T16:00:00Z',
    read: true,
    actionUrl: '/portal/catalog?product=wedding-cake',
    actionLabel: 'View deal',
    icon: 'Tag',
    severity: 'info',
  },
  {
    id: 'notif-g-013',
    type: 'message',
    title: 'New Message from Marcus',
    body: 'Marcus Johnson sent you a message about your upcoming delivery schedule and the new Gelato line.',
    timestamp: '2026-03-05T14:00:00Z',
    read: true,
    actionUrl: '/portal/messages',
    actionLabel: 'Read message',
    icon: 'MessageSquare',
    severity: 'info',
  },
  {
    id: 'notif-g-014',
    type: 'stock_alert',
    title: 'Low Stock: Blue Dream 3.5g',
    body: 'Blue Dream 3.5g is running low in our warehouse — only 48 units remaining. Consider ordering soon.',
    timestamp: '2026-03-05T10:30:00Z',
    read: true,
    actionUrl: '/portal/catalog?product=blue-dream',
    actionLabel: 'Reorder',
    icon: 'AlertTriangle',
    severity: 'warning',
  },
  {
    id: 'notif-g-015',
    type: 'order_update',
    title: 'Order In Production',
    body: 'ORD-2026-0841 is now in production. Your custom Gelato preroll order is being manufactured.',
    timestamp: '2026-03-04T15:00:00Z',
    read: true,
    actionUrl: '/portal/orders/ORD-2026-0841',
    actionLabel: 'View order',
    icon: 'ClipboardCheck',
    severity: 'info',
  },
  {
    id: 'notif-g-016',
    type: 'delivery_alert',
    title: 'Delivery Completed',
    body: 'Your delivery for ORD-2026-0839 was completed at 11:42 AM. Signed by Jake P.',
    timestamp: '2026-03-04T11:45:00Z',
    read: true,
    actionUrl: '/portal/deliveries/del-099',
    actionLabel: 'View receipt',
    icon: 'PackageCheck',
    severity: 'info',
  },
  {
    id: 'notif-g-017',
    type: 'payment_reminder',
    title: 'Payment Due Soon',
    body: 'Invoice INV-2026-0110 for $3,240 is due in 5 days. Set up ACH for automatic payments.',
    timestamp: '2026-03-03T09:00:00Z',
    read: true,
    actionUrl: '/portal/invoices/INV-2026-0110',
    actionLabel: 'Pay now',
    icon: 'CreditCard',
    severity: 'warning',
  },
  {
    id: 'notif-g-018',
    type: 'ai_suggestion',
    title: 'Sales Insight',
    body: 'Your customers love Gelato — it\'s trending 40% higher than last month across Washington. Consider stocking more.',
    timestamp: '2026-03-03T08:00:00Z',
    read: true,
    actionUrl: '/portal/ai-assistant',
    actionLabel: 'Learn more',
    icon: 'Sparkles',
    severity: 'info',
  },
  {
    id: 'notif-g-019',
    type: 'store_order',
    title: 'New Walk-in Order',
    body: 'New walk-in order entered by your budtender. 2 items ready for fulfillment.',
    timestamp: '2026-03-02T16:30:00Z',
    read: true,
    actionUrl: '/portal/store-orders/SO-0995',
    actionLabel: 'View order',
    icon: 'ShoppingBag',
    severity: 'info',
  },
  {
    id: 'notif-g-020',
    type: 'order_update',
    title: 'Order Delivered',
    body: 'ORD-2026-0839 marked as delivered. All 18 units accounted for.',
    timestamp: '2026-03-02T12:00:00Z',
    read: true,
    actionUrl: '/portal/orders/ORD-2026-0839',
    actionLabel: 'View order',
    icon: 'ClipboardCheck',
    severity: 'info',
  },
  {
    id: 'notif-g-021',
    type: 'promotion',
    title: 'Spring Sale Preview',
    body: 'Spring sale starts March 15 — up to 20% off flower and prerolls. Preview the deals now.',
    timestamp: '2026-03-01T10:00:00Z',
    read: true,
    actionUrl: '/portal/promotions',
    actionLabel: 'Preview deals',
    icon: 'Tag',
    severity: 'info',
  },
  {
    id: 'notif-g-022',
    type: 'message',
    title: 'Marcus Shared a Document',
    body: 'Marcus Johnson shared your updated pricing sheet for Q2 2026. Review the new tier pricing.',
    timestamp: '2026-02-28T14:00:00Z',
    read: true,
    actionUrl: '/portal/messages',
    actionLabel: 'View document',
    icon: 'MessageSquare',
    severity: 'info',
  },
  {
    id: 'notif-g-023',
    type: 'delivery_alert',
    title: 'Delivery Rescheduled',
    body: 'Your March 3 delivery has been rescheduled to March 4 due to weather. New window: 10 AM – 2 PM.',
    timestamp: '2026-02-28T09:00:00Z',
    read: true,
    actionUrl: '/portal/deliveries/del-098',
    actionLabel: 'View details',
    icon: 'CalendarCheck',
    severity: 'warning',
  },
  {
    id: 'notif-g-024',
    type: 'stock_alert',
    title: 'Back in Stock: OG Kush 7g',
    body: 'OG Kush 7g is back in stock with 120 units available. Your last order sold through quickly.',
    timestamp: '2026-02-27T11:00:00Z',
    read: true,
    actionUrl: '/portal/catalog?product=og-kush',
    actionLabel: 'Order now',
    icon: 'AlertTriangle',
    severity: 'info',
  },
  {
    id: 'notif-g-025',
    type: 'order_update',
    title: 'Order Packaged',
    body: 'ORD-2026-0837 has been packaged and is ready for dispatch. Delivery will be scheduled shortly.',
    timestamp: '2026-02-26T16:00:00Z',
    read: true,
    actionUrl: '/portal/orders/ORD-2026-0837',
    actionLabel: 'View order',
    icon: 'ClipboardCheck',
    severity: 'info',
  },
  {
    id: 'notif-g-026',
    type: 'new_product',
    title: 'New Edible Line: Frost Gummies',
    body: 'Frost Gummies are here — 10mg THC per piece, 10-pack. Available in Watermelon, Mango, and Mixed Berry.',
    timestamp: '2026-02-25T10:00:00Z',
    read: true,
    actionUrl: '/portal/catalog?category=edibles',
    actionLabel: 'View products',
    icon: 'PackagePlus',
    severity: 'info',
  },
  {
    id: 'notif-g-027',
    type: 'store_order',
    title: 'Store Order Cancelled',
    body: 'Customer Alex M. cancelled their pickup order SO-0990. No action needed — inventory restored.',
    timestamp: '2026-02-24T14:30:00Z',
    read: true,
    actionUrl: '/portal/store-orders/SO-0990',
    actionLabel: 'View details',
    icon: 'ShoppingBag',
    severity: 'info',
  },
  {
    id: 'notif-g-028',
    type: 'payment_reminder',
    title: 'Payment Received',
    body: 'Payment of $2,890 received for invoice INV-2026-0108. Thank you for your prompt payment.',
    timestamp: '2026-02-23T09:00:00Z',
    read: true,
    actionUrl: '/portal/invoices/INV-2026-0108',
    actionLabel: 'View invoice',
    icon: 'CreditCard',
    severity: 'info',
  },
];

const PACIFIC_LEAF_NOTIFICATIONS: PortalNotification[] = [
  {
    id: 'notif-p-001',
    type: 'payment_overdue',
    title: 'Invoice Overdue',
    body: 'Invoice INV-2026-0114 overdue — $1,850. This invoice was due on Feb 22. Please remit payment immediately.',
    timestamp: '2026-03-08T08:00:00Z',
    read: false,
    actionUrl: '/portal/invoices/INV-2026-0114',
    actionLabel: 'Pay now',
    icon: 'AlertOctagon',
    severity: 'urgent',
  },
  {
    id: 'notif-p-002',
    type: 'payment_overdue',
    title: 'Invoice Overdue',
    body: 'Invoice INV-2026-0115 overdue — $2,350. This invoice was due on Feb 28. Contact your rep to discuss a payment plan.',
    timestamp: '2026-03-08T08:00:00Z',
    read: false,
    actionUrl: '/portal/invoices/INV-2026-0115',
    actionLabel: 'Pay now',
    icon: 'AlertOctagon',
    severity: 'urgent',
  },
  {
    id: 'notif-p-003',
    type: 'store_order',
    title: 'New Pickup Order',
    body: 'New pickup order from Jane — Sarah K. ordered 2 items. Review and accept to begin prep.',
    timestamp: '2026-03-07T15:20:00Z',
    read: false,
    actionUrl: '/portal/store-orders/SO-2001',
    actionLabel: 'View order',
    icon: 'ShoppingBag',
    severity: 'info',
  },
  {
    id: 'notif-p-004',
    type: 'payment_reminder',
    title: 'Payment Due in 3 Days',
    body: 'Invoice INV-2026-0116 for $1,420 is due in 3 days. Avoid late fees by paying on time.',
    timestamp: '2026-03-07T09:00:00Z',
    read: false,
    actionUrl: '/portal/invoices/INV-2026-0116',
    actionLabel: 'Pay now',
    icon: 'CreditCard',
    severity: 'warning',
  },
  {
    id: 'notif-p-005',
    type: 'order_update',
    title: 'Order Confirmed',
    body: 'ORD-2026-0850 confirmed. Your re-engagement order of 12 units is being prepared.',
    timestamp: '2026-03-06T14:00:00Z',
    read: true,
    actionUrl: '/portal/orders/ORD-2026-0850',
    actionLabel: 'View order',
    icon: 'ClipboardCheck',
    severity: 'info',
  },
  {
    id: 'notif-p-006',
    type: 'store_order',
    title: 'Order Waiting for Prep',
    body: 'Pickup order from Dutchie is waiting for prep — customer expects pickup in 30 minutes.',
    timestamp: '2026-03-06T11:00:00Z',
    read: true,
    actionUrl: '/portal/store-orders/SO-2000',
    actionLabel: 'Start prep',
    icon: 'ShoppingBag',
    severity: 'warning',
  },
  {
    id: 'notif-p-007',
    type: 'delivery_alert',
    title: 'Delivery Scheduled',
    body: 'Delivery scheduled for March 11 between 1 PM and 4 PM. Please ensure someone is available to receive.',
    timestamp: '2026-03-06T09:00:00Z',
    read: true,
    actionUrl: '/portal/deliveries/del-201',
    actionLabel: 'View details',
    icon: 'CalendarCheck',
    severity: 'info',
  },
  {
    id: 'notif-p-008',
    type: 'promotion',
    title: 'Win-Back Offer: 15% Off First Reorder',
    body: 'Welcome back! Enjoy 15% off your next order as part of our re-engagement program. Offer valid through March 15.',
    timestamp: '2026-03-05T10:00:00Z',
    read: true,
    actionUrl: '/portal/promotions',
    actionLabel: 'Shop now',
    icon: 'Tag',
    severity: 'info',
  },
  {
    id: 'notif-p-009',
    type: 'message',
    title: 'New Message from Daniella',
    body: 'Daniella Reyes sent you a message about your account status and a potential payment plan.',
    timestamp: '2026-03-05T08:30:00Z',
    read: true,
    actionUrl: '/portal/messages',
    actionLabel: 'Read message',
    icon: 'MessageSquare',
    severity: 'info',
  },
  {
    id: 'notif-p-010',
    type: 'order_update',
    title: 'Order Shipped',
    body: 'ORD-2026-0848 shipped. Your delivery is expected on March 7.',
    timestamp: '2026-03-04T16:00:00Z',
    read: true,
    actionUrl: '/portal/orders/ORD-2026-0848',
    actionLabel: 'Track order',
    icon: 'ClipboardCheck',
    severity: 'info',
  },
  {
    id: 'notif-p-011',
    type: 'new_product',
    title: 'New Strains Available',
    body: 'Three new strains just dropped: Gelato, Zkittlez, and Mimosa. Perfect for refreshing your menu.',
    timestamp: '2026-03-04T10:00:00Z',
    read: true,
    actionUrl: '/portal/catalog?filter=new',
    actionLabel: 'View products',
    icon: 'PackagePlus',
    severity: 'info',
  },
  {
    id: 'notif-p-012',
    type: 'delivery_alert',
    title: 'Delivery Completed',
    body: 'Delivery for ORD-2026-0848 completed at 2:15 PM. Signed by Linda T.',
    timestamp: '2026-03-03T14:20:00Z',
    read: true,
    actionUrl: '/portal/deliveries/del-200',
    actionLabel: 'View receipt',
    icon: 'PackageCheck',
    severity: 'info',
  },
  {
    id: 'notif-p-013',
    type: 'stock_alert',
    title: 'Limited Stock: Wedding Cake',
    body: 'Wedding Cake 3.5g has limited availability — only 30 units left. Order soon to secure your allocation.',
    timestamp: '2026-03-03T09:00:00Z',
    read: true,
    actionUrl: '/portal/catalog?product=wedding-cake',
    actionLabel: 'Order now',
    icon: 'AlertTriangle',
    severity: 'warning',
  },
  {
    id: 'notif-p-014',
    type: 'ai_suggestion',
    title: 'Menu Optimization Tip',
    body: 'Based on regional trends, adding Gelato and Zkittlez could increase your basket size by 20%. Want to try a small order?',
    timestamp: '2026-03-02T11:00:00Z',
    read: true,
    actionUrl: '/portal/ai-assistant',
    actionLabel: 'Learn more',
    icon: 'Sparkles',
    severity: 'info',
  },
  {
    id: 'notif-p-015',
    type: 'order_update',
    title: 'Order In Production',
    body: 'ORD-2026-0846 is in production. Your custom preroll order is being rolled and packaged.',
    timestamp: '2026-03-01T15:00:00Z',
    read: true,
    actionUrl: '/portal/orders/ORD-2026-0846',
    actionLabel: 'View order',
    icon: 'ClipboardCheck',
    severity: 'info',
  },
  {
    id: 'notif-p-016',
    type: 'promotion',
    title: 'Preroll Multi-Pack Savings',
    body: 'Buy 24+ preroll packs and save 12%. Great for stocking your bestsellers.',
    timestamp: '2026-03-01T10:00:00Z',
    read: true,
    actionUrl: '/portal/catalog?category=prerolls',
    actionLabel: 'View deals',
    icon: 'Tag',
    severity: 'info',
  },
  {
    id: 'notif-p-017',
    type: 'delivery_alert',
    title: 'Delivery Window Updated',
    body: 'Your March 5 delivery window has been updated to 2 PM – 5 PM due to route optimization.',
    timestamp: '2026-02-28T16:00:00Z',
    read: true,
    actionUrl: '/portal/deliveries/del-199',
    actionLabel: 'View details',
    icon: 'CalendarCheck',
    severity: 'info',
  },
  {
    id: 'notif-p-018',
    type: 'message',
    title: 'Daniella Shared Payment Options',
    body: 'Daniella Reyes shared information about flexible payment options and ACH setup to help you get current.',
    timestamp: '2026-02-27T14:00:00Z',
    read: true,
    actionUrl: '/portal/messages',
    actionLabel: 'Read message',
    icon: 'MessageSquare',
    severity: 'info',
  },
  {
    id: 'notif-p-019',
    type: 'new_product',
    title: 'Frost Beverages Now Available',
    body: 'Frost THC-infused sparkling waters are here — 5mg and 10mg options in Lemon, Berry, and Citrus.',
    timestamp: '2026-02-26T10:00:00Z',
    read: true,
    actionUrl: '/portal/catalog?category=beverages',
    actionLabel: 'View products',
    icon: 'PackagePlus',
    severity: 'info',
  },
  {
    id: 'notif-p-020',
    type: 'order_update',
    title: 'Order Packaged',
    body: 'ORD-2026-0844 has been packaged and labeled. Awaiting carrier pickup for delivery.',
    timestamp: '2026-02-25T15:00:00Z',
    read: true,
    actionUrl: '/portal/orders/ORD-2026-0844',
    actionLabel: 'View order',
    icon: 'ClipboardCheck',
    severity: 'info',
  },
  {
    id: 'notif-p-021',
    type: 'store_order',
    title: 'Pickup Order No-Show',
    body: 'Customer James P. did not pick up their order within 2 hours. The order has been marked as no-show.',
    timestamp: '2026-02-24T17:00:00Z',
    read: true,
    actionUrl: '/portal/store-orders/SO-1998',
    actionLabel: 'View details',
    icon: 'ShoppingBag',
    severity: 'warning',
  },
  {
    id: 'notif-p-022',
    type: 'payment_reminder',
    title: 'Payment Reminder',
    body: 'Friendly reminder: Invoice INV-2026-0113 for $1,680 is due on March 1. Please submit payment on time.',
    timestamp: '2026-02-24T09:00:00Z',
    read: true,
    actionUrl: '/portal/invoices/INV-2026-0113',
    actionLabel: 'Pay now',
    icon: 'CreditCard',
    severity: 'warning',
  },
  {
    id: 'notif-p-023',
    type: 'stock_alert',
    title: 'Blue Dream Restocked',
    body: 'Blue Dream 3.5g and 7g are back in stock with fresh harvest. Order before it sells out again.',
    timestamp: '2026-02-22T11:00:00Z',
    read: true,
    actionUrl: '/portal/catalog?product=blue-dream',
    actionLabel: 'Order now',
    icon: 'AlertTriangle',
    severity: 'info',
  },
  {
    id: 'notif-p-024',
    type: 'promotion',
    title: 'First Reorder Bonus',
    body: 'Place your first reorder this month and get free shipping plus a sample pack of our newest strains.',
    timestamp: '2026-02-20T10:00:00Z',
    read: true,
    actionUrl: '/portal/promotions',
    actionLabel: 'View offer',
    icon: 'Tag',
    severity: 'info',
  },
  {
    id: 'notif-p-025',
    type: 'delivery_alert',
    title: 'Delivery Route Assigned',
    body: 'Your next delivery has been assigned to Route B (East corridor). Driver details will follow 24 hours before.',
    timestamp: '2026-02-18T14:00:00Z',
    read: true,
    actionUrl: '/portal/deliveries',
    actionLabel: 'View schedule',
    icon: 'CalendarCheck',
    severity: 'info',
  },
];

const CASCADE_WELLNESS_NOTIFICATIONS: PortalNotification[] = [
  {
    id: 'notif-c-001',
    type: 'order_update',
    title: 'Order Confirmed',
    body: 'ORD-2026-0852 confirmed. Your first order of 8 units is being prepared. Welcome to Frost!',
    timestamp: '2026-03-08T10:00:00Z',
    read: false,
    actionUrl: '/portal/orders/ORD-2026-0852',
    actionLabel: 'View order',
    icon: 'ClipboardCheck',
    severity: 'info',
  },
  {
    id: 'notif-c-002',
    type: 'delivery_alert',
    title: 'First Delivery Scheduled',
    body: 'Your first delivery is scheduled for March 12 between 10 AM and 1 PM. We\'ll send driver details the day before.',
    timestamp: '2026-03-07T14:00:00Z',
    read: false,
    actionUrl: '/portal/deliveries/del-301',
    actionLabel: 'View details',
    icon: 'CalendarCheck',
    severity: 'info',
  },
  {
    id: 'notif-c-003',
    type: 'order_update',
    title: 'Order In Production',
    body: 'ORD-2026-0852 is in production. Your Blue Dream and Wedding Cake order is being packaged.',
    timestamp: '2026-03-06T16:00:00Z',
    read: true,
    actionUrl: '/portal/orders/ORD-2026-0852',
    actionLabel: 'View order',
    icon: 'ClipboardCheck',
    severity: 'info',
  },
  {
    id: 'notif-c-004',
    type: 'message',
    title: 'Welcome from Marcus',
    body: 'Marcus Johnson sent you a welcome message with tips for getting started on the Frost portal.',
    timestamp: '2026-03-05T10:00:00Z',
    read: true,
    actionUrl: '/portal/messages',
    actionLabel: 'Read message',
    icon: 'MessageSquare',
    severity: 'info',
  },
  {
    id: 'notif-c-005',
    type: 'new_product',
    title: 'Recommended: Starter Pack',
    body: 'Check out our Dispensary Starter Pack — curated selection of top sellers at introductory pricing.',
    timestamp: '2026-03-04T10:00:00Z',
    read: true,
    actionUrl: '/portal/catalog?filter=starter-pack',
    actionLabel: 'View products',
    icon: 'PackagePlus',
    severity: 'info',
  },
  {
    id: 'notif-c-006',
    type: 'delivery_alert',
    title: 'Delivery Setup Complete',
    body: 'Your delivery preferences have been saved — Wednesday mornings, 10 AM – 1 PM. You can change this anytime.',
    timestamp: '2026-03-03T09:00:00Z',
    read: true,
    actionUrl: '/portal/account/delivery',
    actionLabel: 'Edit preferences',
    icon: 'CalendarCheck',
    severity: 'info',
  },
  {
    id: 'notif-c-007',
    type: 'order_update',
    title: 'Account Activated',
    body: 'Your Frost B2B account is fully activated. Browse the catalog and place your first order anytime.',
    timestamp: '2026-03-02T10:00:00Z',
    read: true,
    actionUrl: '/portal/catalog',
    actionLabel: 'Browse catalog',
    icon: 'ClipboardCheck',
    severity: 'info',
  },
  {
    id: 'notif-c-008',
    type: 'promotion',
    title: 'New Account Discount',
    body: '10% off your first 3 orders as a new Frost partner. Discount applied automatically at checkout.',
    timestamp: '2026-03-01T10:00:00Z',
    read: true,
    actionUrl: '/portal/promotions',
    actionLabel: 'View offer',
    icon: 'Tag',
    severity: 'info',
  },
  {
    id: 'notif-c-009',
    type: 'order_update',
    title: 'Sample Pack Shipped',
    body: 'Your complimentary sample pack has shipped. Expect delivery within 2 business days.',
    timestamp: '2026-02-28T14:00:00Z',
    read: true,
    actionUrl: '/portal/orders/ORD-2026-0849',
    actionLabel: 'Track shipment',
    icon: 'ClipboardCheck',
    severity: 'info',
  },
  {
    id: 'notif-c-010',
    type: 'message',
    title: 'Product Recommendations from Marcus',
    body: 'Marcus Johnson shared personalized product recommendations based on your store location and customer demographics.',
    timestamp: '2026-02-26T11:00:00Z',
    read: true,
    actionUrl: '/portal/messages',
    actionLabel: 'Read message',
    icon: 'MessageSquare',
    severity: 'info',
  },
  {
    id: 'notif-c-011',
    type: 'delivery_alert',
    title: 'Sample Pack Delivered',
    body: 'Your sample pack was delivered at 10:30 AM. Let Marcus know what you think of the products.',
    timestamp: '2026-02-25T10:35:00Z',
    read: true,
    actionUrl: '/portal/deliveries/del-300',
    actionLabel: 'View details',
    icon: 'PackageCheck',
    severity: 'info',
  },
  {
    id: 'notif-c-012',
    type: 'new_product',
    title: 'Best Sellers This Month',
    body: 'Check out what other dispensaries in your area are ordering — Blue Dream and Wedding Cake lead the pack.',
    timestamp: '2026-02-23T10:00:00Z',
    read: true,
    actionUrl: '/portal/catalog?sort=popular',
    actionLabel: 'View products',
    icon: 'PackagePlus',
    severity: 'info',
  },
  {
    id: 'notif-c-013',
    type: 'ai_suggestion',
    title: 'Getting Started Tip',
    body: 'Try our AI ordering assistant to quickly build your first order. It can recommend products based on your store type.',
    timestamp: '2026-02-21T10:00:00Z',
    read: true,
    actionUrl: '/portal/ai-assistant',
    actionLabel: 'Try it',
    icon: 'Sparkles',
    severity: 'info',
  },
  {
    id: 'notif-c-014',
    type: 'order_update',
    title: 'Welcome to Frost',
    body: 'Your B2B portal account has been created. Explore the catalog, set up delivery preferences, and reach out to Marcus with any questions.',
    timestamp: '2026-02-20T09:00:00Z',
    read: true,
    actionUrl: '/portal/dashboard',
    actionLabel: 'Get started',
    icon: 'ClipboardCheck',
    severity: 'info',
  },
  {
    id: 'notif-c-015',
    type: 'promotion',
    title: 'Refer a Dispensary',
    body: 'Know another dispensary that would love Frost products? Refer them and both of you get $100 in credit.',
    timestamp: '2026-02-18T10:00:00Z',
    read: true,
    actionUrl: '/portal/referrals',
    actionLabel: 'Refer now',
    icon: 'Tag',
    severity: 'info',
  },
];

const NOTIFICATIONS_BY_ACCOUNT: Record<string, PortalNotification[]> = {
  'acct-1': GREENFIELD_NOTIFICATIONS,
  'acct-2': PACIFIC_LEAF_NOTIFICATIONS,
  'acct-3': CASCADE_WELLNESS_NOTIFICATIONS,
};

export function getNotificationsForAccount(accountId: string): PortalNotification[] {
  return NOTIFICATIONS_BY_ACCOUNT[accountId] ?? [];
}
