import type { PortalProduct, PortalVolumeBreak } from '../types';
import { PORTAL_ACCOUNTS } from './accounts';

// ─── Helpers ─────────────────────────────────────────────────────

function volumeBreaks(basePrice: number): PortalVolumeBreak[] {
  return [
    { minQuantity: 10, discountPercent: 5, pricePerUnit: +(basePrice * 0.95).toFixed(2) },
    { minQuantity: 25, discountPercent: 10, pricePerUnit: +(basePrice * 0.90).toFixed(2) },
    { minQuantity: 50, discountPercent: 15, pricePerUnit: +(basePrice * 0.85).toFixed(2) },
  ];
}

const IMG = '/images/portal/placeholder.jpg';

// ─── Flower (15 products) ────────────────────────────────────────

const FLOWER: PortalProduct[] = [
  // Wedding Cake
  {
    id: 'prod-fl-wc-35',
    name: 'Wedding Cake 3.5g',
    category: 'flower',
    subCategory: '3.5g Jar',
    strainName: 'Wedding Cake',
    strainType: 'hybrid',
    thcMin: 25, thcMax: 30, cbdMin: 0.1, cbdMax: 0.5,
    packageSize: '3.5g',
    basePrice: 35, unitPrice: 35,
    volumeBreaks: volumeBreaks(35),
    availableQuantity: 240,
    brand: 'Frost Cannabis', productLine: 'Premium Flower',
    description: 'Rich vanilla and tangy notes with a heavy body high. Top-shelf hybrid perfection.',
    imageUrl: IMG, isNew: false, isPopular: true, inStock: true,
  },
  {
    id: 'prod-fl-wc-7',
    name: 'Wedding Cake 7g',
    category: 'flower',
    subCategory: '7g Jar',
    strainName: 'Wedding Cake',
    strainType: 'hybrid',
    thcMin: 25, thcMax: 30, cbdMin: 0.1, cbdMax: 0.5,
    packageSize: '7g',
    basePrice: 65, unitPrice: 65,
    volumeBreaks: volumeBreaks(65),
    availableQuantity: 120,
    brand: 'Frost Cannabis', productLine: 'Premium Flower',
    description: 'Rich vanilla and tangy notes with a heavy body high. Quarter ounce value.',
    imageUrl: IMG, isNew: false, isPopular: true, inStock: true,
  },
  {
    id: 'prod-fl-wc-14',
    name: 'Wedding Cake 14g',
    category: 'flower',
    subCategory: '14g Jar',
    strainName: 'Wedding Cake',
    strainType: 'hybrid',
    thcMin: 25, thcMax: 30, cbdMin: 0.1, cbdMax: 0.5,
    packageSize: '14g',
    basePrice: 120, unitPrice: 120,
    volumeBreaks: volumeBreaks(120),
    availableQuantity: 60,
    brand: 'Frost Cannabis', productLine: 'Premium Flower',
    description: 'Rich vanilla and tangy notes. Half ounce for your heaviest hitters.',
    imageUrl: IMG, isNew: false, isPopular: true, inStock: true,
  },

  // Blue Dream
  {
    id: 'prod-fl-bd-35',
    name: 'Blue Dream 3.5g',
    category: 'flower',
    subCategory: '3.5g Jar',
    strainName: 'Blue Dream',
    strainType: 'sativa',
    thcMin: 21, thcMax: 25, cbdMin: 0.5, cbdMax: 1.0,
    packageSize: '3.5g',
    basePrice: 30, unitPrice: 30,
    volumeBreaks: volumeBreaks(30),
    availableQuantity: 300,
    brand: 'Frost Cannabis', productLine: 'Premium Flower',
    description: 'Sweet berry aroma with gentle cerebral invigoration. A West Coast classic.',
    imageUrl: IMG, isNew: false, isPopular: true, inStock: true,
  },
  {
    id: 'prod-fl-bd-7',
    name: 'Blue Dream 7g',
    category: 'flower',
    subCategory: '7g Jar',
    strainName: 'Blue Dream',
    strainType: 'sativa',
    thcMin: 21, thcMax: 25, cbdMin: 0.5, cbdMax: 1.0,
    packageSize: '7g',
    basePrice: 55, unitPrice: 55,
    volumeBreaks: volumeBreaks(55),
    availableQuantity: 150,
    brand: 'Frost Cannabis', productLine: 'Premium Flower',
    description: 'Sweet berry aroma with gentle cerebral invigoration. Quarter ounce.',
    imageUrl: IMG, isNew: false, isPopular: true, inStock: true,
  },
  {
    id: 'prod-fl-bd-14',
    name: 'Blue Dream 14g',
    category: 'flower',
    subCategory: '14g Jar',
    strainName: 'Blue Dream',
    strainType: 'sativa',
    thcMin: 21, thcMax: 25, cbdMin: 0.5, cbdMax: 1.0,
    packageSize: '14g',
    basePrice: 105, unitPrice: 105,
    volumeBreaks: volumeBreaks(105),
    availableQuantity: 80,
    brand: 'Frost Cannabis', productLine: 'Premium Flower',
    description: 'Sweet berry aroma. Half ounce for steady rotation on your shelves.',
    imageUrl: IMG, isNew: false, isPopular: true, inStock: true,
  },

  // OG Kush
  {
    id: 'prod-fl-og-35',
    name: 'OG Kush 3.5g',
    category: 'flower',
    subCategory: '3.5g Jar',
    strainName: 'OG Kush',
    strainType: 'indica',
    thcMin: 23, thcMax: 28, cbdMin: 0.2, cbdMax: 0.8,
    packageSize: '3.5g',
    basePrice: 38, unitPrice: 38,
    volumeBreaks: volumeBreaks(38),
    availableQuantity: 180,
    brand: 'Frost Cannabis', productLine: 'Premium Flower',
    description: 'Earthy pine with sour lemon. The original heavy indica for deep relaxation.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },
  {
    id: 'prod-fl-og-7',
    name: 'OG Kush 7g',
    category: 'flower',
    subCategory: '7g Jar',
    strainName: 'OG Kush',
    strainType: 'indica',
    thcMin: 23, thcMax: 28, cbdMin: 0.2, cbdMax: 0.8,
    packageSize: '7g',
    basePrice: 70, unitPrice: 70,
    volumeBreaks: volumeBreaks(70),
    availableQuantity: 90,
    brand: 'Frost Cannabis', productLine: 'Premium Flower',
    description: 'Earthy pine with sour lemon. Quarter ounce of the classic indica.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },
  {
    id: 'prod-fl-og-14',
    name: 'OG Kush 14g',
    category: 'flower',
    subCategory: '14g Jar',
    strainName: 'OG Kush',
    strainType: 'indica',
    thcMin: 23, thcMax: 28, cbdMin: 0.2, cbdMax: 0.8,
    packageSize: '14g',
    basePrice: 130, unitPrice: 130,
    volumeBreaks: volumeBreaks(130),
    availableQuantity: 45,
    brand: 'Frost Cannabis', productLine: 'Premium Flower',
    description: 'Earthy pine with sour lemon. Half ounce for bulk indica buyers.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },

  // Gelato
  {
    id: 'prod-fl-gel-35',
    name: 'Gelato 3.5g',
    category: 'flower',
    subCategory: '3.5g Jar',
    strainName: 'Gelato',
    strainType: 'hybrid',
    thcMin: 24, thcMax: 28, cbdMin: 0.1, cbdMax: 0.3,
    packageSize: '3.5g',
    basePrice: 40, unitPrice: 40,
    volumeBreaks: volumeBreaks(40),
    availableQuantity: 200,
    brand: 'Frost Cannabis', productLine: 'Premium Flower',
    description: 'Dessert-like sweetness with a euphoric, creative buzz. New to the lineup.',
    imageUrl: IMG, isNew: true, isPopular: false, inStock: true,
  },
  {
    id: 'prod-fl-gel-7',
    name: 'Gelato 7g',
    category: 'flower',
    subCategory: '7g Jar',
    strainName: 'Gelato',
    strainType: 'hybrid',
    thcMin: 24, thcMax: 28, cbdMin: 0.1, cbdMax: 0.3,
    packageSize: '7g',
    basePrice: 75, unitPrice: 75,
    volumeBreaks: volumeBreaks(75),
    availableQuantity: 100,
    brand: 'Frost Cannabis', productLine: 'Premium Flower',
    description: 'Dessert-like sweetness with a euphoric, creative buzz. Quarter ounce.',
    imageUrl: IMG, isNew: true, isPopular: false, inStock: true,
  },
  {
    id: 'prod-fl-gel-14',
    name: 'Gelato 14g',
    category: 'flower',
    subCategory: '14g Jar',
    strainName: 'Gelato',
    strainType: 'hybrid',
    thcMin: 24, thcMax: 28, cbdMin: 0.1, cbdMax: 0.3,
    packageSize: '14g',
    basePrice: 140, unitPrice: 140,
    volumeBreaks: volumeBreaks(140),
    availableQuantity: 0,
    brand: 'Frost Cannabis', productLine: 'Premium Flower',
    description: 'Dessert-like sweetness. Half ounce — currently restocking.',
    imageUrl: IMG, isNew: true, isPopular: false, inStock: false,
  },

  // Zkittlez
  {
    id: 'prod-fl-zk-35',
    name: 'Zkittlez 3.5g',
    category: 'flower',
    subCategory: '3.5g Jar',
    strainName: 'Zkittlez',
    strainType: 'indica',
    thcMin: 20, thcMax: 24, cbdMin: 0.3, cbdMax: 0.7,
    packageSize: '3.5g',
    basePrice: 32, unitPrice: 32,
    volumeBreaks: volumeBreaks(32),
    availableQuantity: 260,
    brand: 'Frost Cannabis', productLine: 'Premium Flower',
    description: 'Tropical fruit candy flavor with a calm, focused indica effect.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },
  {
    id: 'prod-fl-zk-7',
    name: 'Zkittlez 7g',
    category: 'flower',
    subCategory: '7g Jar',
    strainName: 'Zkittlez',
    strainType: 'indica',
    thcMin: 20, thcMax: 24, cbdMin: 0.3, cbdMax: 0.7,
    packageSize: '7g',
    basePrice: 60, unitPrice: 60,
    volumeBreaks: volumeBreaks(60),
    availableQuantity: 130,
    brand: 'Frost Cannabis', productLine: 'Premium Flower',
    description: 'Tropical fruit candy flavor with a calm, focused effect. Quarter ounce.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },
  {
    id: 'prod-fl-zk-14',
    name: 'Zkittlez 14g',
    category: 'flower',
    subCategory: '14g Jar',
    strainName: 'Zkittlez',
    strainType: 'indica',
    thcMin: 20, thcMax: 24, cbdMin: 0.3, cbdMax: 0.7,
    packageSize: '14g',
    basePrice: 110, unitPrice: 110,
    volumeBreaks: volumeBreaks(110),
    availableQuantity: 65,
    brand: 'Frost Cannabis', productLine: 'Premium Flower',
    description: 'Tropical fruit candy. Half ounce for your indica-dominant shelves.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },
];

// ─── Prerolls (10 products) ──────────────────────────────────────

const PREROLLS: PortalProduct[] = [
  // Wedding Cake
  {
    id: 'prod-pr-wc-single',
    name: 'Wedding Cake Preroll',
    category: 'prerolls',
    subCategory: 'Single',
    strainName: 'Wedding Cake',
    strainType: 'hybrid',
    thcMin: 25, thcMax: 30, cbdMin: 0.1, cbdMax: 0.5,
    packageSize: '1g Single',
    basePrice: 12, unitPrice: 12,
    volumeBreaks: volumeBreaks(12),
    availableQuantity: 500,
    brand: 'Frost Cannabis', productLine: 'Ready Rolls',
    description: 'Hand-rolled Wedding Cake in a king-size cone. Ready to light.',
    imageUrl: IMG, isNew: false, isPopular: true, inStock: true,
  },
  {
    id: 'prod-pr-wc-3pk',
    name: 'Wedding Cake 3-Pack',
    category: 'prerolls',
    subCategory: '3-Pack',
    strainName: 'Wedding Cake',
    strainType: 'hybrid',
    thcMin: 25, thcMax: 30, cbdMin: 0.1, cbdMax: 0.5,
    packageSize: '3x 1g',
    basePrice: 32, unitPrice: 32,
    volumeBreaks: volumeBreaks(32),
    availableQuantity: 200,
    brand: 'Frost Cannabis', productLine: 'Ready Rolls',
    description: 'Three king-size Wedding Cake cones in a resealable tube.',
    imageUrl: IMG, isNew: false, isPopular: true, inStock: true,
  },

  // Blue Dream
  {
    id: 'prod-pr-bd-single',
    name: 'Blue Dream Preroll',
    category: 'prerolls',
    subCategory: 'Single',
    strainName: 'Blue Dream',
    strainType: 'sativa',
    thcMin: 21, thcMax: 25, cbdMin: 0.5, cbdMax: 1.0,
    packageSize: '1g Single',
    basePrice: 10, unitPrice: 10,
    volumeBreaks: volumeBreaks(10),
    availableQuantity: 600,
    brand: 'Frost Cannabis', productLine: 'Ready Rolls',
    description: 'Classic Blue Dream sativa in a ready-to-go cone.',
    imageUrl: IMG, isNew: false, isPopular: true, inStock: true,
  },
  {
    id: 'prod-pr-bd-3pk',
    name: 'Blue Dream 3-Pack',
    category: 'prerolls',
    subCategory: '3-Pack',
    strainName: 'Blue Dream',
    strainType: 'sativa',
    thcMin: 21, thcMax: 25, cbdMin: 0.5, cbdMax: 1.0,
    packageSize: '3x 1g',
    basePrice: 28, unitPrice: 28,
    volumeBreaks: volumeBreaks(28),
    availableQuantity: 250,
    brand: 'Frost Cannabis', productLine: 'Ready Rolls',
    description: 'Three Blue Dream cones for daytime sessions.',
    imageUrl: IMG, isNew: false, isPopular: true, inStock: true,
  },

  // OG Kush
  {
    id: 'prod-pr-og-single',
    name: 'OG Kush Preroll',
    category: 'prerolls',
    subCategory: 'Single',
    strainName: 'OG Kush',
    strainType: 'indica',
    thcMin: 23, thcMax: 28, cbdMin: 0.2, cbdMax: 0.8,
    packageSize: '1g Single',
    basePrice: 13, unitPrice: 13,
    volumeBreaks: volumeBreaks(13),
    availableQuantity: 400,
    brand: 'Frost Cannabis', productLine: 'Ready Rolls',
    description: 'OG Kush hand-rolled in a king-size cone for evening wind-down.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },
  {
    id: 'prod-pr-og-3pk',
    name: 'OG Kush 3-Pack',
    category: 'prerolls',
    subCategory: '3-Pack',
    strainName: 'OG Kush',
    strainType: 'indica',
    thcMin: 23, thcMax: 28, cbdMin: 0.2, cbdMax: 0.8,
    packageSize: '3x 1g',
    basePrice: 35, unitPrice: 35,
    volumeBreaks: volumeBreaks(35),
    availableQuantity: 180,
    brand: 'Frost Cannabis', productLine: 'Ready Rolls',
    description: 'Three OG Kush king-size cones in a resealable tube.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },

  // Gelato
  {
    id: 'prod-pr-gel-single',
    name: 'Gelato Preroll',
    category: 'prerolls',
    subCategory: 'Single',
    strainName: 'Gelato',
    strainType: 'hybrid',
    thcMin: 24, thcMax: 28, cbdMin: 0.1, cbdMax: 0.3,
    packageSize: '1g Single',
    basePrice: 14, unitPrice: 14,
    volumeBreaks: volumeBreaks(14),
    availableQuantity: 350,
    brand: 'Frost Cannabis', productLine: 'Ready Rolls',
    description: 'Gelato cone with dessert-like flavor. New strain in the Ready Rolls lineup.',
    imageUrl: IMG, isNew: true, isPopular: false, inStock: true,
  },
  {
    id: 'prod-pr-gel-3pk',
    name: 'Gelato 3-Pack',
    category: 'prerolls',
    subCategory: '3-Pack',
    strainName: 'Gelato',
    strainType: 'hybrid',
    thcMin: 24, thcMax: 28, cbdMin: 0.1, cbdMax: 0.3,
    packageSize: '3x 1g',
    basePrice: 38, unitPrice: 38,
    volumeBreaks: volumeBreaks(38),
    availableQuantity: 0,
    brand: 'Frost Cannabis', productLine: 'Ready Rolls',
    description: 'Three Gelato cones — arriving in next production run.',
    imageUrl: IMG, isNew: true, isPopular: false, inStock: false,
  },

  // Zkittlez
  {
    id: 'prod-pr-zk-single',
    name: 'Zkittlez Preroll',
    category: 'prerolls',
    subCategory: 'Single',
    strainName: 'Zkittlez',
    strainType: 'indica',
    thcMin: 20, thcMax: 24, cbdMin: 0.3, cbdMax: 0.7,
    packageSize: '1g Single',
    basePrice: 11, unitPrice: 11,
    volumeBreaks: volumeBreaks(11),
    availableQuantity: 450,
    brand: 'Frost Cannabis', productLine: 'Ready Rolls',
    description: 'Zkittlez cone bursting with tropical fruit flavor.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },
  {
    id: 'prod-pr-zk-3pk',
    name: 'Zkittlez 3-Pack',
    category: 'prerolls',
    subCategory: '3-Pack',
    strainName: 'Zkittlez',
    strainType: 'indica',
    thcMin: 20, thcMax: 24, cbdMin: 0.3, cbdMax: 0.7,
    packageSize: '3x 1g',
    basePrice: 30, unitPrice: 30,
    volumeBreaks: volumeBreaks(30),
    availableQuantity: 190,
    brand: 'Frost Cannabis', productLine: 'Ready Rolls',
    description: 'Three Zkittlez cones for the candy-lovers on your shelf.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },
];

// ─── Vaporizers (8 products) ─────────────────────────────────────

const VAPORIZERS: PortalProduct[] = [
  // Wedding Cake
  {
    id: 'prod-vap-wc-05',
    name: 'Wedding Cake Cart 0.5g',
    category: 'vaporizers',
    subCategory: '0.5g Cart',
    strainName: 'Wedding Cake',
    strainType: 'hybrid',
    thcMin: 80, thcMax: 90, cbdMin: 0, cbdMax: 0.5,
    packageSize: '0.5g',
    basePrice: 30, unitPrice: 30,
    volumeBreaks: volumeBreaks(30),
    availableQuantity: 320,
    brand: 'Frost Cannabis', productLine: 'Frost Vapor',
    description: 'Wedding Cake distillate in a 510-thread cart. Smooth vapor, big flavor.',
    imageUrl: IMG, isNew: false, isPopular: true, inStock: true,
  },
  {
    id: 'prod-vap-wc-10',
    name: 'Wedding Cake Cart 1g',
    category: 'vaporizers',
    subCategory: '1g Cart',
    strainName: 'Wedding Cake',
    strainType: 'hybrid',
    thcMin: 80, thcMax: 90, cbdMin: 0, cbdMax: 0.5,
    packageSize: '1g',
    basePrice: 50, unitPrice: 50,
    volumeBreaks: volumeBreaks(50),
    availableQuantity: 160,
    brand: 'Frost Cannabis', productLine: 'Frost Vapor',
    description: 'Full-gram Wedding Cake distillate cart. Value size for heavy hitters.',
    imageUrl: IMG, isNew: false, isPopular: true, inStock: true,
  },

  // Blue Dream
  {
    id: 'prod-vap-bd-05',
    name: 'Blue Dream Cart 0.5g',
    category: 'vaporizers',
    subCategory: '0.5g Cart',
    strainName: 'Blue Dream',
    strainType: 'sativa',
    thcMin: 78, thcMax: 88, cbdMin: 0.5, cbdMax: 1.0,
    packageSize: '0.5g',
    basePrice: 28, unitPrice: 28,
    volumeBreaks: volumeBreaks(28),
    availableQuantity: 280,
    brand: 'Frost Cannabis', productLine: 'Frost Vapor',
    description: 'Blue Dream sativa distillate. Berry notes on every pull.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },
  {
    id: 'prod-vap-bd-10',
    name: 'Blue Dream Cart 1g',
    category: 'vaporizers',
    subCategory: '1g Cart',
    strainName: 'Blue Dream',
    strainType: 'sativa',
    thcMin: 78, thcMax: 88, cbdMin: 0.5, cbdMax: 1.0,
    packageSize: '1g',
    basePrice: 45, unitPrice: 45,
    volumeBreaks: volumeBreaks(45),
    availableQuantity: 140,
    brand: 'Frost Cannabis', productLine: 'Frost Vapor',
    description: 'Full-gram Blue Dream cart for the all-day sativa fans.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },

  // OG Kush
  {
    id: 'prod-vap-og-05',
    name: 'OG Kush Cart 0.5g',
    category: 'vaporizers',
    subCategory: '0.5g Cart',
    strainName: 'OG Kush',
    strainType: 'indica',
    thcMin: 82, thcMax: 92, cbdMin: 0.2, cbdMax: 0.8,
    packageSize: '0.5g',
    basePrice: 32, unitPrice: 32,
    volumeBreaks: volumeBreaks(32),
    availableQuantity: 260,
    brand: 'Frost Cannabis', productLine: 'Frost Vapor',
    description: 'OG Kush indica distillate. Pine-forward with deep relaxation.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },
  {
    id: 'prod-vap-og-10',
    name: 'OG Kush Cart 1g',
    category: 'vaporizers',
    subCategory: '1g Cart',
    strainName: 'OG Kush',
    strainType: 'indica',
    thcMin: 82, thcMax: 92, cbdMin: 0.2, cbdMax: 0.8,
    packageSize: '1g',
    basePrice: 52, unitPrice: 52,
    volumeBreaks: volumeBreaks(52),
    availableQuantity: 0,
    brand: 'Frost Cannabis', productLine: 'Frost Vapor',
    description: 'Full-gram OG Kush cart — currently restocking.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: false,
  },

  // Gelato
  {
    id: 'prod-vap-gel-05',
    name: 'Gelato Cart 0.5g',
    category: 'vaporizers',
    subCategory: '0.5g Cart',
    strainName: 'Gelato',
    strainType: 'hybrid',
    thcMin: 84, thcMax: 92, cbdMin: 0.1, cbdMax: 0.3,
    packageSize: '0.5g',
    basePrice: 35, unitPrice: 35,
    volumeBreaks: volumeBreaks(35),
    availableQuantity: 220,
    brand: 'Frost Cannabis', productLine: 'Frost Vapor',
    description: 'Gelato distillate with sweet, creamy terpenes. New to Frost Vapor.',
    imageUrl: IMG, isNew: true, isPopular: false, inStock: true,
  },
  {
    id: 'prod-vap-gel-10',
    name: 'Gelato Cart 1g',
    category: 'vaporizers',
    subCategory: '1g Cart',
    strainName: 'Gelato',
    strainType: 'hybrid',
    thcMin: 84, thcMax: 92, cbdMin: 0.1, cbdMax: 0.3,
    packageSize: '1g',
    basePrice: 55, unitPrice: 55,
    volumeBreaks: volumeBreaks(55),
    availableQuantity: 110,
    brand: 'Frost Cannabis', productLine: 'Frost Vapor',
    description: 'Full-gram Gelato cart. Dessert-forward and potent. New release.',
    imageUrl: IMG, isNew: true, isPopular: false, inStock: true,
  },
];

// ─── Concentrates (8 products) ───────────────────────────────────

const CONCENTRATES: PortalProduct[] = [
  // Wedding Cake
  {
    id: 'prod-con-wc-sh',
    name: 'Wedding Cake Shatter',
    category: 'concentrates',
    subCategory: 'Shatter',
    strainName: 'Wedding Cake',
    strainType: 'hybrid',
    thcMin: 75, thcMax: 85, cbdMin: 0, cbdMax: 0.3,
    packageSize: '1g',
    basePrice: 35, unitPrice: 35,
    volumeBreaks: volumeBreaks(35),
    availableQuantity: 180,
    brand: 'Frost Cannabis', productLine: 'Frost Extracts',
    description: 'Glass-like Wedding Cake shatter. Snap, dab, enjoy.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },
  {
    id: 'prod-con-wc-lr',
    name: 'Wedding Cake Live Resin',
    category: 'concentrates',
    subCategory: 'Live Resin',
    strainName: 'Wedding Cake',
    strainType: 'hybrid',
    thcMin: 70, thcMax: 82, cbdMin: 0.1, cbdMax: 0.5,
    packageSize: '1g',
    basePrice: 48, unitPrice: 48,
    volumeBreaks: volumeBreaks(48),
    availableQuantity: 120,
    brand: 'Frost Cannabis', productLine: 'Frost Extracts',
    description: 'Flash-frozen Wedding Cake live resin. Full terpene spectrum preserved.',
    imageUrl: IMG, isNew: false, isPopular: true, inStock: true,
  },

  // Blue Dream
  {
    id: 'prod-con-bd-sh',
    name: 'Blue Dream Shatter',
    category: 'concentrates',
    subCategory: 'Shatter',
    strainName: 'Blue Dream',
    strainType: 'sativa',
    thcMin: 72, thcMax: 82, cbdMin: 0.5, cbdMax: 1.0,
    packageSize: '1g',
    basePrice: 30, unitPrice: 30,
    volumeBreaks: volumeBreaks(30),
    availableQuantity: 200,
    brand: 'Frost Cannabis', productLine: 'Frost Extracts',
    description: 'Blue Dream shatter for a clean, uplifting dab.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },
  {
    id: 'prod-con-bd-lr',
    name: 'Blue Dream Live Resin',
    category: 'concentrates',
    subCategory: 'Live Resin',
    strainName: 'Blue Dream',
    strainType: 'sativa',
    thcMin: 68, thcMax: 80, cbdMin: 0.5, cbdMax: 1.0,
    packageSize: '1g',
    basePrice: 42, unitPrice: 42,
    volumeBreaks: volumeBreaks(42),
    availableQuantity: 140,
    brand: 'Frost Cannabis', productLine: 'Frost Extracts',
    description: 'Flash-frozen Blue Dream live resin with berry-forward terps.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },

  // OG Kush
  {
    id: 'prod-con-og-sh',
    name: 'OG Kush Shatter',
    category: 'concentrates',
    subCategory: 'Shatter',
    strainName: 'OG Kush',
    strainType: 'indica',
    thcMin: 76, thcMax: 86, cbdMin: 0.2, cbdMax: 0.8,
    packageSize: '1g',
    basePrice: 38, unitPrice: 38,
    volumeBreaks: volumeBreaks(38),
    availableQuantity: 150,
    brand: 'Frost Cannabis', productLine: 'Frost Extracts',
    description: 'OG Kush shatter with earthy, piney flavor. Heavy indica dab.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },
  {
    id: 'prod-con-og-lr',
    name: 'OG Kush Live Resin',
    category: 'concentrates',
    subCategory: 'Live Resin',
    strainName: 'OG Kush',
    strainType: 'indica',
    thcMin: 72, thcMax: 84, cbdMin: 0.2, cbdMax: 0.8,
    packageSize: '1g',
    basePrice: 52, unitPrice: 52,
    volumeBreaks: volumeBreaks(52),
    availableQuantity: 100,
    brand: 'Frost Cannabis', productLine: 'Frost Extracts',
    description: 'Flash-frozen OG Kush live resin. Full terpene indica experience.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },

  // Gelato
  {
    id: 'prod-con-gel-sh',
    name: 'Gelato Shatter',
    category: 'concentrates',
    subCategory: 'Shatter',
    strainName: 'Gelato',
    strainType: 'hybrid',
    thcMin: 78, thcMax: 88, cbdMin: 0.1, cbdMax: 0.3,
    packageSize: '1g',
    basePrice: 40, unitPrice: 40,
    volumeBreaks: volumeBreaks(40),
    availableQuantity: 170,
    brand: 'Frost Cannabis', productLine: 'Frost Extracts',
    description: 'Gelato shatter with sweet, creamy dab experience. New extract.',
    imageUrl: IMG, isNew: true, isPopular: false, inStock: true,
  },
  {
    id: 'prod-con-gel-lr',
    name: 'Gelato Live Resin',
    category: 'concentrates',
    subCategory: 'Live Resin',
    strainName: 'Gelato',
    strainType: 'hybrid',
    thcMin: 74, thcMax: 86, cbdMin: 0.1, cbdMax: 0.3,
    packageSize: '1g',
    basePrice: 55, unitPrice: 55,
    volumeBreaks: volumeBreaks(55),
    availableQuantity: 90,
    brand: 'Frost Cannabis', productLine: 'Frost Extracts',
    description: 'Flash-frozen Gelato live resin. Dessert terps at their peak. New release.',
    imageUrl: IMG, isNew: true, isPopular: false, inStock: true,
  },
];

// ─── Edibles (6 products) ────────────────────────────────────────

const EDIBLES: PortalProduct[] = [
  {
    id: 'prod-ed-gum-10',
    name: 'Gummies 10mg 10-Pack',
    category: 'edibles',
    subCategory: 'Gummies',
    strainName: 'Mixed',
    strainType: 'hybrid',
    thcMin: 10, thcMax: 10, cbdMin: 0, cbdMax: 0,
    packageSize: '10-pack (100mg total)',
    basePrice: 18, unitPrice: 18,
    volumeBreaks: volumeBreaks(18),
    availableQuantity: 500,
    brand: 'Frost Cannabis', productLine: 'Frost Edibles',
    description: 'Assorted fruit gummies, 10mg THC each. Beginner-friendly dosing.',
    imageUrl: IMG, isNew: false, isPopular: true, inStock: true,
  },
  {
    id: 'prod-ed-gum-25',
    name: 'Gummies 25mg 10-Pack',
    category: 'edibles',
    subCategory: 'Gummies',
    strainName: 'Mixed',
    strainType: 'hybrid',
    thcMin: 25, thcMax: 25, cbdMin: 0, cbdMax: 0,
    packageSize: '10-pack (250mg total)',
    basePrice: 30, unitPrice: 30,
    volumeBreaks: volumeBreaks(30),
    availableQuantity: 350,
    brand: 'Frost Cannabis', productLine: 'Frost Edibles',
    description: 'Assorted fruit gummies, 25mg THC each. For experienced consumers.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },
  {
    id: 'prod-ed-gum-50',
    name: 'Gummies 50mg 10-Pack',
    category: 'edibles',
    subCategory: 'Gummies',
    strainName: 'Mixed',
    strainType: 'hybrid',
    thcMin: 50, thcMax: 50, cbdMin: 0, cbdMax: 0,
    packageSize: '10-pack (500mg total)',
    basePrice: 45, unitPrice: 45,
    volumeBreaks: volumeBreaks(45),
    availableQuantity: 180,
    brand: 'Frost Cannabis', productLine: 'Frost Edibles',
    description: 'High-dose gummies, 50mg THC each. For the seasoned edible enthusiast.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },
  {
    id: 'prod-ed-choc-10',
    name: 'Chocolate Bar 10mg 4-Bar',
    category: 'edibles',
    subCategory: 'Chocolate',
    strainName: 'Mixed',
    strainType: 'hybrid',
    thcMin: 10, thcMax: 10, cbdMin: 0, cbdMax: 0,
    packageSize: '4-bar (40mg total)',
    basePrice: 15, unitPrice: 15,
    volumeBreaks: volumeBreaks(15),
    availableQuantity: 400,
    brand: 'Frost Cannabis', productLine: 'Frost Edibles',
    description: 'Dark chocolate bars, 10mg per piece. Smooth, melt-in-your-mouth dosing.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },
  {
    id: 'prod-ed-choc-25',
    name: 'Chocolate Bar 25mg 4-Bar',
    category: 'edibles',
    subCategory: 'Chocolate',
    strainName: 'Mixed',
    strainType: 'hybrid',
    thcMin: 25, thcMax: 25, cbdMin: 0, cbdMax: 0,
    packageSize: '4-bar (100mg total)',
    basePrice: 28, unitPrice: 28,
    volumeBreaks: volumeBreaks(28),
    availableQuantity: 250,
    brand: 'Frost Cannabis', productLine: 'Frost Edibles',
    description: 'Dark chocolate bars, 25mg per piece. Rich cacao with a potent kick.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },
  {
    id: 'prod-ed-choc-50',
    name: 'Chocolate Bar 50mg 4-Bar',
    category: 'edibles',
    subCategory: 'Chocolate',
    strainName: 'Mixed',
    strainType: 'hybrid',
    thcMin: 50, thcMax: 50, cbdMin: 0, cbdMax: 0,
    packageSize: '4-bar (200mg total)',
    basePrice: 42, unitPrice: 42,
    volumeBreaks: volumeBreaks(42),
    availableQuantity: 0,
    brand: 'Frost Cannabis', productLine: 'Frost Edibles',
    description: 'High-dose chocolate bars, 50mg per piece. Currently restocking.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: false,
  },
];

// ─── Beverages (3 products) ──────────────────────────────────────

const BEVERAGES: PortalProduct[] = [
  {
    id: 'prod-bev-selt-10',
    name: 'Frost Seltzer 10mg',
    category: 'beverages',
    subCategory: 'Seltzer',
    strainName: 'Mixed',
    strainType: 'hybrid',
    thcMin: 10, thcMax: 10, cbdMin: 0, cbdMax: 0,
    packageSize: '12oz Can',
    basePrice: 12, unitPrice: 12,
    volumeBreaks: volumeBreaks(12),
    availableQuantity: 600,
    brand: 'Frost Cannabis', productLine: 'Frost Drinks',
    description: 'Crisp, citrus-infused THC seltzer. Zero sugar, fast onset.',
    imageUrl: IMG, isNew: false, isPopular: true, inStock: true,
  },
  {
    id: 'prod-bev-selt-25',
    name: 'Frost Seltzer 25mg',
    category: 'beverages',
    subCategory: 'Seltzer',
    strainName: 'Mixed',
    strainType: 'hybrid',
    thcMin: 25, thcMax: 25, cbdMin: 0, cbdMax: 0,
    packageSize: '12oz Can',
    basePrice: 18, unitPrice: 18,
    volumeBreaks: volumeBreaks(18),
    availableQuantity: 350,
    brand: 'Frost Cannabis', productLine: 'Frost Drinks',
    description: 'Higher-dose citrus THC seltzer for experienced consumers.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },
  {
    id: 'prod-bev-tinc-500',
    name: 'Frost Tincture 500mg',
    category: 'beverages',
    subCategory: 'Tincture',
    strainName: 'Mixed',
    strainType: 'hybrid',
    thcMin: 500, thcMax: 500, cbdMin: 0, cbdMax: 0,
    packageSize: '30ml Bottle',
    basePrice: 30, unitPrice: 30,
    volumeBreaks: volumeBreaks(30),
    availableQuantity: 200,
    brand: 'Frost Cannabis', productLine: 'Frost Drinks',
    description: 'Sublingual MCT oil tincture. Precise dosing with the included dropper.',
    imageUrl: IMG, isNew: false, isPopular: false, inStock: true,
  },
];

// ─── Combined catalog ────────────────────────────────────────────

export const PORTAL_PRODUCTS: PortalProduct[] = [
  ...FLOWER,
  ...PREROLLS,
  ...VAPORIZERS,
  ...CONCENTRATES,
  ...EDIBLES,
  ...BEVERAGES,
];

// ─── Tier pricing helper ─────────────────────────────────────────

const TIER_DISCOUNTS: Record<number, number> = {
  1: 0.15, // 15% off
  2: 0.08, // 8% off
  3: 0,    // full price
};

export function getProductsForAccount(accountId: string): PortalProduct[] {
  const account = PORTAL_ACCOUNTS.find((a) => a.id === accountId);
  if (!account) return PORTAL_PRODUCTS;

  const discount = TIER_DISCOUNTS[account.pricingTier] ?? 0;
  if (discount === 0) return PORTAL_PRODUCTS;

  return PORTAL_PRODUCTS.map((product) => {
    const tierPrice = +(product.basePrice * (1 - discount)).toFixed(2);
    return {
      ...product,
      unitPrice: tierPrice,
      volumeBreaks: product.volumeBreaks.map((vb) => ({
        ...vb,
        pricePerUnit: +(tierPrice * (1 - vb.discountPercent / 100)).toFixed(2),
      })),
    };
  });
}
