import type { PortalProductionItem } from '../types';

export const PORTAL_PRODUCTION_ITEMS: PortalProductionItem[] = [
  // Cultivation items
  {
    id: 'prod-001',
    type: 'cultivation',
    strainName: 'Gelato',
    category: 'flower',
    currentStage: 'Flowering',
    estimatedDate: '2026-04-05',
    estimatedQuantity: '120 units (3.5g)',
    reserved: true,
  },
  {
    id: 'prod-002',
    type: 'cultivation',
    strainName: 'Wedding Cake',
    category: 'flower',
    currentStage: 'Drying',
    estimatedDate: '2026-03-18',
    estimatedQuantity: '200 units (3.5g), 80 units (7g)',
    reserved: false,
  },
  {
    id: 'prod-003',
    type: 'cultivation',
    strainName: 'Blue Dream',
    category: 'flower',
    currentStage: 'Curing',
    estimatedDate: '2026-03-14',
    estimatedQuantity: '150 units (3.5g), 60 units (7g)',
    reserved: false,
  },
  {
    id: 'prod-004',
    type: 'cultivation',
    strainName: 'Zkittlez',
    category: 'flower',
    currentStage: 'Vegetative',
    estimatedDate: '2026-04-25',
    estimatedQuantity: '100 units (3.5g)',
    reserved: false,
  },
  {
    id: 'prod-005',
    type: 'cultivation',
    strainName: 'Mimosa',
    category: 'flower',
    currentStage: 'Flowering',
    estimatedDate: '2026-04-10',
    estimatedQuantity: '90 units (3.5g), 40 units (7g)',
    reserved: true,
  },
  {
    id: 'prod-006',
    type: 'cultivation',
    strainName: 'OG Kush',
    category: 'flower',
    currentStage: 'Drying',
    estimatedDate: '2026-03-20',
    estimatedQuantity: '180 units (3.5g), 70 units (7g)',
    reserved: false,
  },
  // Manufacturing items
  {
    id: 'prod-007',
    type: 'manufacturing',
    strainName: 'Gelato',
    productName: 'Gelato Live Resin Cart 1g',
    category: 'vaporizers',
    currentStage: 'Extraction',
    estimatedDate: '2026-03-22',
    estimatedQuantity: '200 carts',
    reserved: true,
  },
  {
    id: 'prod-008',
    type: 'manufacturing',
    strainName: 'Zkittlez',
    productName: 'Zkittlez Live Resin 1g',
    category: 'concentrates',
    currentStage: 'Purging',
    estimatedDate: '2026-03-15',
    estimatedQuantity: '100 jars',
    reserved: false,
  },
  {
    id: 'prod-009',
    type: 'manufacturing',
    strainName: 'Wedding Cake',
    productName: 'Wedding Cake Badder 1g',
    category: 'concentrates',
    currentStage: 'Whipping',
    estimatedDate: '2026-03-12',
    estimatedQuantity: '80 jars',
    reserved: false,
  },
  {
    id: 'prod-010',
    type: 'manufacturing',
    strainName: 'Mixed',
    productName: 'Frost Gummies Watermelon 10-Pack',
    category: 'edibles',
    currentStage: 'Infusion',
    estimatedDate: '2026-03-25',
    estimatedQuantity: '500 packs',
    reserved: false,
  },
  {
    id: 'prod-011',
    type: 'manufacturing',
    strainName: 'Blue Dream',
    productName: 'Blue Dream Cart 1g',
    category: 'vaporizers',
    currentStage: 'Filling',
    estimatedDate: '2026-03-10',
    estimatedQuantity: '150 carts',
    reserved: true,
  },
  {
    id: 'prod-012',
    type: 'manufacturing',
    strainName: 'Mixed',
    productName: 'Frost Sparkling Water Variety 12-Pack',
    category: 'beverages',
    currentStage: 'Bottling',
    estimatedDate: '2026-04-01',
    estimatedQuantity: '300 cases',
    reserved: false,
  },
];
