"""
Frost Seed Script
-----------------
Seeds the Supabase database with 20 strains and 42 products.
Does NOT seed accounts, contacts, or interactions — those start empty.

Usage:
    python seed.py

Requires environment variables:
    SUPABASE_URL
    SUPABASE_SERVICE_ROLE_KEY
"""

import os
import sys

try:
    from supabase import create_client
except ImportError:
    print("Install dependencies first: pip install supabase python-dotenv")
    sys.exit(1)

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # dotenv is optional if env vars are set directly

SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_SERVICE_ROLE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")

if not SUPABASE_URL or not SUPABASE_SERVICE_ROLE_KEY:
    print("Error: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set")
    sys.exit(1)

supabase = create_client(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)

# ---------------------------------------------------------------------------
# Strains (20)
# ---------------------------------------------------------------------------

STRAINS = [
    {"name": "Wedding Cake", "slug": "wedding-cake", "strain_type": "hybrid", "lineage": "Triangle Mints x Animal Mints", "thc_min": 25, "thc_max": 29, "cbd_min": 0, "cbd_max": 1, "terpenes": ["Myrcene", "Limonene", "Caryophyllene"], "effects": ["Relaxed", "Euphoric", "Creative"], "flavor_notes": ["Vanilla", "Sweet", "Earthy"], "description": "A decadent hybrid with rich vanilla and sweet earthy undertones. Wedding Cake delivers a deeply relaxing body high paired with a clear-headed euphoria that sparks creativity.", "difficulty": "moderate", "image_url": "https://images.unsplash.com/photo-1603909223429-69bb7101f420?w=800&q=80"},
    {"name": "Blue Dream", "slug": "blue-dream", "strain_type": "sativa", "lineage": "Blueberry x Haze", "thc_min": 19, "thc_max": 24, "cbd_min": 0, "cbd_max": 1, "terpenes": ["Myrcene", "Pinene", "Caryophyllene"], "effects": ["Uplifted", "Creative", "Energetic"], "flavor_notes": ["Blueberry", "Sweet", "Herbal"], "description": "A beloved sativa-dominant classic known for its sweet blueberry aroma and gentle cerebral invigoration.", "difficulty": "easy", "image_url": "https://images.unsplash.com/photo-1586013049587-c4dfe4a5a6be?w=800&q=80"},
    {"name": "Gelato", "slug": "gelato", "strain_type": "hybrid", "lineage": "Sunset Sherbet x Thin Mint GSC", "thc_min": 22, "thc_max": 28, "cbd_min": 0, "cbd_max": 1, "terpenes": ["Limonene", "Caryophyllene", "Humulene"], "effects": ["Relaxed", "Happy", "Euphoric"], "flavor_notes": ["Sweet", "Citrus", "Fruity"], "description": "Named after the Italian dessert, Gelato delivers a sweet citrus and fruity flavor profile that feels like a treat.", "difficulty": "moderate", "image_url": "https://images.unsplash.com/photo-1601579112934-17ac2aa86292?w=800&q=80"},
    {"name": "GSC (Girl Scout Cookies)", "slug": "gsc-girl-scout-cookies", "strain_type": "hybrid", "lineage": "OG Kush x Durban Poison", "thc_min": 24, "thc_max": 28, "cbd_min": 0, "cbd_max": 1, "terpenes": ["Caryophyllene", "Limonene", "Linalool"], "effects": ["Euphoric", "Happy", "Relaxed"], "flavor_notes": ["Sweet", "Earthy", "Mint"], "description": "A powerhouse hybrid that blends sweet, earthy, and minty flavors into an unforgettable experience.", "difficulty": "advanced", "image_url": "https://images.unsplash.com/photo-1604660913767-95f736a4cee0?w=800&q=80"},
    {"name": "Zkittlez", "slug": "zkittlez", "strain_type": "indica", "lineage": "Grape Ape x Grapefruit", "thc_min": 20, "thc_max": 24, "cbd_min": 0, "cbd_max": 1, "terpenes": ["Linalool", "Caryophyllene", "Humulene"], "effects": ["Relaxed", "Happy", "Sleepy"], "flavor_notes": ["Tropical", "Berry", "Sweet"], "description": "A candy-sweet indica that lives up to its name with an explosion of tropical and berry flavors.", "difficulty": "easy", "image_url": "https://images.unsplash.com/photo-1587754363725-8a862e9f5c13?w=800&q=80"},
    {"name": "OG Kush", "slug": "og-kush", "strain_type": "hybrid", "lineage": "Chemdawg x Lemon Thai x Hindu Kush", "thc_min": 20, "thc_max": 26, "cbd_min": 0, "cbd_max": 1, "terpenes": ["Myrcene", "Limonene", "Caryophyllene"], "effects": ["Relaxed", "Euphoric", "Happy"], "flavor_notes": ["Pine", "Earthy", "Woody"], "description": "The legendary backbone of West Coast cannabis culture.", "difficulty": "moderate", "image_url": "https://images.unsplash.com/photo-1589484280067-2e6b3a1975df?w=800&q=80"},
    {"name": "Jack Herer", "slug": "jack-herer", "strain_type": "sativa", "lineage": "Haze x Northern Lights x Shiva Skunk", "thc_min": 18, "thc_max": 23, "cbd_min": 0, "cbd_max": 1, "terpenes": ["Terpinolene", "Pinene", "Myrcene"], "effects": ["Energetic", "Creative", "Focused"], "flavor_notes": ["Pine", "Spicy", "Herbal"], "description": "Named after the legendary cannabis activist, Jack Herer is a crisp, piney sativa that fuels focus and creativity.", "difficulty": "moderate", "image_url": "https://images.unsplash.com/photo-1560743641-3914f2c45636?w=800&q=80"},
    {"name": "Gorilla Glue #4", "slug": "gorilla-glue-4", "strain_type": "hybrid", "lineage": "Chem Sister x Sour Dubb x Chocolate Diesel", "thc_min": 25, "thc_max": 30, "cbd_min": 0, "cbd_max": 1, "terpenes": ["Caryophyllene", "Myrcene", "Limonene"], "effects": ["Relaxed", "Euphoric", "Uplifted"], "flavor_notes": ["Pine", "Diesel", "Chocolate"], "description": "A heavy-hitting hybrid famous for its resinous buds that glue your fingers together.", "difficulty": "moderate", "image_url": "https://images.unsplash.com/photo-1603386329225-868f9b1ee6b2?w=800&q=80"},
    {"name": "Northern Lights", "slug": "northern-lights", "strain_type": "indica", "lineage": "Afghani landrace", "thc_min": 16, "thc_max": 21, "cbd_min": 1, "cbd_max": 2, "terpenes": ["Myrcene", "Pinene", "Linalool"], "effects": ["Relaxed", "Sleepy", "Happy"], "flavor_notes": ["Pine", "Sweet", "Earthy"], "description": "One of the most iconic indicas ever cultivated, Northern Lights wraps you in a blanket of dreamy relaxation.", "difficulty": "easy", "image_url": "https://images.unsplash.com/photo-1567112229437-a4bae1edbd29?w=800&q=80"},
    {"name": "Runtz", "slug": "runtz", "strain_type": "hybrid", "lineage": "Zkittlez x Gelato", "thc_min": 24, "thc_max": 29, "cbd_min": 0, "cbd_max": 1, "terpenes": ["Limonene", "Linalool", "Caryophyllene"], "effects": ["Euphoric", "Relaxed", "Giggly"], "flavor_notes": ["Candy", "Tropical", "Sweet"], "description": "A modern masterpiece born from two legendary parents, Runtz bursts with candy-sweet tropical flavors.", "difficulty": "advanced", "image_url": "https://images.unsplash.com/photo-1616690002498-1915efab3249?w=800&q=80"},
    {"name": "Purple Punch", "slug": "purple-punch", "strain_type": "indica", "lineage": "Larry OG x Granddaddy Purple", "thc_min": 18, "thc_max": 25, "cbd_min": 0, "cbd_max": 1, "terpenes": ["Limonene", "Caryophyllene", "Pinene"], "effects": ["Relaxed", "Sleepy", "Happy"], "flavor_notes": ["Grape", "Blueberry", "Sweet"], "description": "A knockout indica that tastes like a bowl of grape Kool-Aid with a blueberry muffin chaser.", "difficulty": "easy", "image_url": "https://images.unsplash.com/photo-1585063560740-8b1a6ee23d40?w=800&q=80"},
    {"name": "Sour Diesel", "slug": "sour-diesel", "strain_type": "sativa", "lineage": "Chemdawg 91 x Super Skunk", "thc_min": 20, "thc_max": 25, "cbd_min": 0, "cbd_max": 1, "terpenes": ["Myrcene", "Limonene", "Caryophyllene"], "effects": ["Energetic", "Uplifted", "Creative"], "flavor_notes": ["Diesel", "Citrus", "Pungent"], "description": "A fast-acting sativa legend with an unmistakable pungent diesel aroma.", "difficulty": "moderate", "image_url": "https://images.unsplash.com/photo-1602168946913-1b98fc30a120?w=800&q=80"},
    {"name": "Pineapple Express", "slug": "pineapple-express", "strain_type": "hybrid", "lineage": "Trainwreck x Hawaiian", "thc_min": 19, "thc_max": 25, "cbd_min": 0, "cbd_max": 1, "terpenes": ["Myrcene", "Pinene", "Caryophyllene"], "effects": ["Happy", "Uplifted", "Energetic"], "flavor_notes": ["Pineapple", "Tropical", "Cedar"], "description": "A tropical hybrid that lives up to the hype with bright pineapple and mango flavors.", "difficulty": "easy", "image_url": "https://images.unsplash.com/photo-1605651698242-ced249e3a029?w=800&q=80"},
    {"name": "Mimosa", "slug": "mimosa", "strain_type": "sativa", "lineage": "Clementine x Purple Punch", "thc_min": 19, "thc_max": 27, "cbd_min": 0, "cbd_max": 1, "terpenes": ["Limonene", "Myrcene", "Pinene"], "effects": ["Uplifted", "Energetic", "Happy"], "flavor_notes": ["Citrus", "Tropical", "Orange"], "description": "Like its brunch-time namesake, Mimosa greets you with a burst of bright citrus and tangy tropical fruit.", "difficulty": "easy", "image_url": "https://images.unsplash.com/photo-1588685648889-854efd75e0af?w=800&q=80"},
    {"name": "Dosidos", "slug": "dosidos", "strain_type": "indica", "lineage": "GSC x Face Off OG", "thc_min": 21, "thc_max": 28, "cbd_min": 0, "cbd_max": 1, "terpenes": ["Limonene", "Linalool", "Caryophyllene"], "effects": ["Relaxed", "Euphoric", "Sleepy"], "flavor_notes": ["Lime", "Sweet", "Earthy"], "description": "A potent indica-leaning hybrid that pairs floral lime and sweet earthy notes.", "difficulty": "moderate", "image_url": "https://images.unsplash.com/photo-1596296986438-11a05e0a2d68?w=800&q=80"},
    {"name": "MAC (Miracle Alien Cookies)", "slug": "mac-miracle-alien-cookies", "strain_type": "hybrid", "lineage": "Alien Cookies x Starfighter x Columbian", "thc_min": 20, "thc_max": 26, "cbd_min": 0, "cbd_max": 1, "terpenes": ["Limonene", "Caryophyllene", "Myrcene"], "effects": ["Euphoric", "Creative", "Relaxed"], "flavor_notes": ["Citrus", "Diesel", "Floral"], "description": "An exotic hybrid that lives up to its miraculous name with a dazzling trichome coat.", "difficulty": "advanced", "image_url": "https://images.unsplash.com/photo-1598976665699-0e5a2f91c3f3?w=800&q=80"},
    {"name": "Biscotti", "slug": "biscotti", "strain_type": "indica", "lineage": "Gelato 25 x South Florida OG", "thc_min": 21, "thc_max": 28, "cbd_min": 0, "cbd_max": 1, "terpenes": ["Limonene", "Caryophyllene", "Myrcene"], "effects": ["Relaxed", "Happy", "Euphoric"], "flavor_notes": ["Cookie", "Nutty", "Sweet"], "description": "A dessert-forward indica with rich cookie dough and nutty flavor notes.", "difficulty": "moderate", "image_url": "https://images.unsplash.com/photo-1603816244457-7e535c2c3b60?w=800&q=80"},
    {"name": "Ice Cream Cake", "slug": "ice-cream-cake", "strain_type": "indica", "lineage": "Wedding Cake x Gelato 33", "thc_min": 20, "thc_max": 25, "cbd_min": 0, "cbd_max": 1, "terpenes": ["Limonene", "Caryophyllene", "Linalool"], "effects": ["Relaxed", "Sleepy", "Happy"], "flavor_notes": ["Vanilla", "Cream", "Sweet"], "description": "A creamy, vanilla-forward indica that tastes exactly like its name suggests.", "difficulty": "moderate", "image_url": "https://images.unsplash.com/photo-1600353068867-5765f2a5e312?w=800&q=80"},
    {"name": "Trainwreck", "slug": "trainwreck", "strain_type": "sativa", "lineage": "Mexican x Thai x Afghani", "thc_min": 18, "thc_max": 25, "cbd_min": 0, "cbd_max": 1, "terpenes": ["Myrcene", "Terpinolene", "Pinene"], "effects": ["Euphoric", "Energetic", "Creative"], "flavor_notes": ["Lemon", "Pine", "Spicy"], "description": "A hard-hitting sativa that slams into you with a rush of euphoric energy and sharp mental clarity.", "difficulty": "easy", "image_url": "https://images.unsplash.com/photo-1567189710413-f1b8f30bfe5c?w=800&q=80"},
    {"name": "Durban Poison", "slug": "durban-poison", "strain_type": "sativa", "lineage": "South African landrace", "thc_min": 15, "thc_max": 25, "cbd_min": 0, "cbd_max": 1, "terpenes": ["Terpinolene", "Myrcene", "Ocimene"], "effects": ["Energetic", "Focused", "Uplifted"], "flavor_notes": ["Sweet", "Anise", "Spicy"], "description": "A pure sativa landrace from the port city of Durban, South Africa.", "difficulty": "easy", "image_url": "https://images.unsplash.com/photo-1563822249542-bee7439c1e89?w=800&q=80"},
]

# ---------------------------------------------------------------------------
# Products (42)
# ---------------------------------------------------------------------------

img = lambda photo_id: f"https://images.unsplash.com/photo-{photo_id}?w=600&q=80"

PRODUCTS = [
    # FLOWER (7)
    {"name": "Blue Dream Flower 3.5g", "slug": "blue-dream-flower-3-5g", "sku": "FL-BD-8TH", "brand": "Frost Farms", "category": "flower", "strain_name": "Blue Dream", "strain_type": "sativa", "description": "Sweet berry aroma meets hazy cerebral lift.", "price": 28, "is_new": False, "is_featured": True, "package_sizes": ["3.5g"], "terpenes": ["Myrcene", "Caryophyllene", "Pinene"], "effects": ["Creative", "Uplifted", "Relaxed", "Focused"], "flavor_notes": ["Blueberry", "Sweet", "Herbal"], "image_url": img("1603909223429-69bb7101f420")},
    {"name": "Wedding Cake Flower 3.5g", "slug": "wedding-cake-flower-3-5g", "sku": "FL-WC-8TH", "brand": "Frost Farms", "category": "flower", "strain_name": "Wedding Cake", "strain_type": "hybrid", "description": "Rich vanilla frosting on the inhale, tangy pepper on the exhale.", "price": 32, "is_new": True, "is_featured": True, "package_sizes": ["3.5g"], "terpenes": ["Limonene", "Caryophyllene", "Myrcene"], "effects": ["Relaxed", "Euphoric", "Creative", "Calm"], "flavor_notes": ["Vanilla", "Pepper", "Sweet Dough"], "image_url": img("1586190848861-99aa4a171e90")},
    {"name": "OG Kush Flower 7g", "slug": "og-kush-flower-7g", "sku": "FL-OGK-QTR", "brand": "Frost Farms", "category": "flower", "strain_name": "OG Kush", "strain_type": "hybrid", "description": "Fuel-forward and piney with earthy depth.", "price": 45, "is_new": False, "is_featured": False, "package_sizes": ["7g"], "terpenes": ["Myrcene", "Limonene", "Caryophyllene"], "effects": ["Relaxed", "Euphoric", "Social", "Uplifted"], "flavor_notes": ["Pine", "Fuel", "Earth"], "image_url": img("1560348957-dda0b91d1a2c")},
    {"name": "Girl Scout Cookies Flower 3.5g", "slug": "girl-scout-cookies-flower-3-5g", "sku": "FL-GSC-8TH", "brand": "Frost Farms", "category": "flower", "strain_name": "GSC", "strain_type": "hybrid", "description": "A sweet, minty exhale followed by a full-body wave.", "price": 30, "is_new": False, "is_featured": False, "package_sizes": ["3.5g"], "terpenes": ["Caryophyllene", "Limonene", "Humulene"], "effects": ["Euphoric", "Relaxed", "Creative", "Social"], "flavor_notes": ["Mint", "Cookie", "Sweet Earth"], "image_url": img("1587754167882-6c2ea2e3480a")},
    {"name": "Jack Herer Flower 28g", "slug": "jack-herer-flower-28g", "sku": "FL-JH-OZ", "brand": "Frost Farms", "category": "flower", "strain_name": "Jack Herer", "strain_type": "sativa", "description": "Spicy pine and bright citrus ignite a clear-headed, energizing buzz.", "price": 120, "is_new": True, "is_featured": False, "package_sizes": ["28g"], "terpenes": ["Terpinolene", "Pinene", "Ocimene"], "effects": ["Focused", "Creative", "Uplifted", "Energized"], "flavor_notes": ["Pine", "Spice", "Citrus"], "image_url": img("1589398934083-926b5e59ec6c")},
    {"name": "Northern Lights Flower 3.5g", "slug": "northern-lights-flower-3-5g", "sku": "FL-NL-8TH", "brand": "Frost Farms", "category": "flower", "strain_name": "Northern Lights", "strain_type": "indica", "description": "Honeyed sweetness and resinous pine draw you into deep, dreamy relaxation.", "price": 26, "is_new": False, "is_featured": False, "package_sizes": ["3.5g"], "terpenes": ["Myrcene", "Caryophyllene", "Pinene"], "effects": ["Relaxed", "Sleepy", "Calm", "Peaceful"], "flavor_notes": ["Honey", "Pine", "Sweet Earth"], "image_url": img("1567284788076-5f21e9abc39a")},
    {"name": "Purple Punch Flower 3.5g", "slug": "purple-punch-flower-3-5g", "sku": "FL-PP-8TH", "brand": "Frost Farms", "category": "flower", "strain_name": "Purple Punch", "strain_type": "indica", "description": "Grape candy and blueberry muffin on the nose with a velvet body melt.", "price": 30, "is_new": True, "is_featured": False, "package_sizes": ["3.5g"], "terpenes": ["Limonene", "Myrcene", "Caryophyllene"], "effects": ["Relaxed", "Sleepy", "Euphoric", "Calm"], "flavor_notes": ["Grape", "Blueberry", "Vanilla"], "image_url": img("1590076084489-6b38b9c12bd8")},

    # PREROLL (7)
    {"name": "Blue Dream Preroll 1g", "slug": "blue-dream-preroll-1g", "sku": "PR-BD-1G", "brand": "Frost Farms", "category": "preroll", "strain_name": "Blue Dream", "strain_type": "sativa", "description": "Grab-and-go berry bliss.", "price": 6, "is_new": False, "is_featured": True, "package_sizes": ["1g"], "terpenes": ["Myrcene", "Caryophyllene", "Pinene"], "effects": ["Creative", "Uplifted", "Relaxed", "Focused"], "flavor_notes": ["Blueberry", "Sweet", "Herbal"], "image_url": img("1576086213369-97a306d36557")},
    {"name": "OG Kush 6-Pack Prerolls", "slug": "og-kush-6-pack-prerolls", "sku": "PR-OGK-6PK", "brand": "Frost Farms", "category": "preroll", "strain_name": "OG Kush", "strain_type": "hybrid", "description": "Six half-gram joints of classic OG.", "price": 12, "is_new": False, "is_featured": False, "package_sizes": ["6 x 0.5g"], "terpenes": ["Myrcene", "Limonene", "Caryophyllene"], "effects": ["Relaxed", "Euphoric", "Social", "Uplifted"], "flavor_notes": ["Pine", "Fuel", "Earth"], "image_url": img("1584468148313-1e43e3e73e22")},
    {"name": "Gorilla Glue Preroll 1g", "slug": "gorilla-glue-preroll-1g", "sku": "PR-GG-1G", "brand": "Frost Farms", "category": "preroll", "strain_name": "Gorilla Glue", "strain_type": "hybrid", "description": "Diesel and chocolate swirl in a heavy-hitting roll.", "price": 5, "is_new": True, "is_featured": False, "package_sizes": ["1g"], "terpenes": ["Caryophyllene", "Myrcene", "Limonene"], "effects": ["Relaxed", "Euphoric", "Creative", "Calm"], "flavor_notes": ["Diesel", "Chocolate", "Pine"], "image_url": img("1585063560633-1b4c59e30e5f")},
    {"name": "Sour Diesel Infused Preroll 1.5g", "slug": "sour-diesel-infused-preroll-1-5g", "sku": "PR-SD-INFUSED", "brand": "Frost Farms", "category": "preroll", "strain_name": "Sour Diesel", "strain_type": "sativa", "description": "Concentrate-dipped and kief-coated for maximum punch.", "price": 10, "is_new": True, "is_featured": True, "package_sizes": ["1.5g"], "terpenes": ["Caryophyllene", "Myrcene", "Limonene"], "effects": ["Energized", "Focused", "Uplifted", "Creative"], "flavor_notes": ["Diesel", "Citrus", "Pungent"], "image_url": img("1599137271736-0c0ca1f05358")},
    {"name": "Northern Lights 3-Pack Prerolls", "slug": "northern-lights-3-pack-prerolls", "sku": "PR-NL-3PK", "brand": "Frost Farms", "category": "preroll", "strain_name": "Northern Lights", "strain_type": "indica", "description": "Three half-gram indica rolls for winding down.", "price": 8, "is_new": False, "is_featured": False, "package_sizes": ["3 x 0.5g"], "terpenes": ["Myrcene", "Caryophyllene", "Pinene"], "effects": ["Relaxed", "Sleepy", "Calm", "Peaceful"], "flavor_notes": ["Honey", "Pine", "Earth"], "image_url": img("1560183006-b2e7a0ac94d6")},
    {"name": "Mixed Strain Variety 6-Pack", "slug": "mixed-strain-variety-6-pack", "sku": "PR-MX-VARIETY", "brand": "Frost Farms", "category": "preroll", "strain_name": "Mixed", "strain_type": "hybrid", "description": "Six strains, six moods.", "price": 11, "is_new": False, "is_featured": False, "package_sizes": ["6 x 0.5g"], "terpenes": ["Myrcene", "Limonene", "Terpinolene"], "effects": ["Social", "Creative", "Relaxed", "Uplifted"], "flavor_notes": ["Mixed", "Fruity", "Earthy"], "image_url": img("1579154204601-c0a3fc01a4e3")},
    {"name": "Sour Diesel Preroll 1g", "slug": "sour-diesel-preroll-1g", "sku": "PR-SD-1G", "brand": "Frost Farms", "category": "preroll", "strain_name": "Sour Diesel", "strain_type": "sativa", "description": "Pungent fuel and zesty lemon in a quick-light single gram.", "price": 5, "is_new": True, "is_featured": False, "package_sizes": ["1g"], "terpenes": ["Caryophyllene", "Limonene", "Myrcene"], "effects": ["Energized", "Focused", "Uplifted", "Social"], "flavor_notes": ["Diesel", "Lemon", "Pungent"], "image_url": img("1588484628369-dd8c4d442e08")},

    # VAPORIZER (7)
    {"name": "Distillate Cartridge 1g", "slug": "distillate-cartridge-1g", "sku": "VP-DIST-1G", "brand": "Glacier Extracts", "category": "vaporizer", "sub_category": "Cartridge", "strain_type": "hybrid", "description": "Crystal-clear distillate with botanical terpenes.", "price": 22, "is_new": False, "is_featured": True, "package_sizes": ["1g"], "terpenes": ["Myrcene", "Limonene", "Linalool"], "effects": ["Relaxed", "Uplifted", "Social", "Calm"], "flavor_notes": ["Clean", "Citrus", "Floral"], "image_url": img("1570439261067-e9e0da0c9a73")},
    {"name": "Live Resin Pod 0.5g", "slug": "live-resin-pod-0-5g", "sku": "VP-LR-05G", "brand": "Glacier Extracts", "category": "vaporizer", "sub_category": "Pod", "strain_type": "indica", "description": "Flash-frozen live resin captures the whole plant.", "price": 28, "is_new": True, "is_featured": False, "package_sizes": ["0.5g"], "terpenes": ["Myrcene", "Caryophyllene", "Linalool"], "effects": ["Relaxed", "Sleepy", "Calm", "Peaceful"], "flavor_notes": ["Earthy", "Herbal", "Sweet"], "image_url": img("1560246611-e0c0da6d3c59")},
    {"name": "Live Resin Cartridge 1g", "slug": "live-resin-cartridge-1g", "sku": "VP-LR-1G", "brand": "Glacier Extracts", "category": "vaporizer", "sub_category": "Cartridge", "strain_type": "sativa", "description": "Full-spectrum live resin in a generous one-gram cart.", "price": 35, "is_new": False, "is_featured": True, "package_sizes": ["1g"], "terpenes": ["Terpinolene", "Pinene", "Ocimene"], "effects": ["Focused", "Creative", "Energized", "Uplifted"], "flavor_notes": ["Citrus", "Pine", "Tropical"], "image_url": img("1593272030074-ec0e4c648b66")},
    {"name": "Disposable Vape 0.5g", "slug": "disposable-vape-0-5g", "sku": "VP-DISP-05G", "brand": "Glacier Extracts", "category": "vaporizer", "sub_category": "Disposable", "strain_type": "sativa", "description": "No charging, no cartridge swaps.", "price": 18, "is_new": False, "is_featured": False, "package_sizes": ["0.5g"], "terpenes": ["Limonene", "Pinene", "Terpinolene"], "effects": ["Energized", "Uplifted", "Creative", "Focused"], "flavor_notes": ["Lemon", "Pine", "Sweet"], "image_url": img("1559703248-2da52b93a08b")},
    {"name": "Disposable Vape 1g", "slug": "disposable-vape-1g", "sku": "VP-DISP-1G", "brand": "Glacier Extracts", "category": "vaporizer", "sub_category": "Disposable", "strain_type": "indica", "description": "Double the capacity for extended weekends.", "price": 22, "is_new": True, "is_featured": False, "package_sizes": ["1g"], "terpenes": ["Myrcene", "Linalool", "Caryophyllene"], "effects": ["Relaxed", "Sleepy", "Calm", "Peaceful"], "flavor_notes": ["Berry", "Lavender", "Earth"], "image_url": img("1587324438442-aff883ad1d1e")},
    {"name": "Terpene Cartridge 0.5g", "slug": "terpene-cartridge-0-5g", "sku": "VP-TERP-05G", "brand": "Glacier Extracts", "category": "vaporizer", "sub_category": "Cartridge", "strain_type": "hybrid", "description": "Strain-matched botanical terpenes layered over refined distillate.", "price": 20, "is_new": False, "is_featured": False, "package_sizes": ["0.5g"], "terpenes": ["Caryophyllene", "Limonene", "Myrcene"], "effects": ["Relaxed", "Social", "Uplifted", "Creative"], "flavor_notes": ["Tropical", "Spice", "Citrus"], "image_url": img("1598378859658-2a0b86cc0959")},
    {"name": "CDT Cartridge 1g", "slug": "cdt-cartridge-1g", "sku": "VP-CDT-1G", "brand": "Glacier Extracts", "category": "vaporizer", "sub_category": "Cartridge", "strain_type": "sativa", "description": "Cannabis-derived terpenes paired with potent distillate.", "price": 32, "is_new": True, "is_featured": False, "package_sizes": ["1g"], "terpenes": ["Terpinolene", "Ocimene", "Limonene"], "effects": ["Focused", "Energized", "Creative", "Uplifted"], "flavor_notes": ["Citrus", "Floral", "Herbal"], "image_url": img("1600001852005-e3ed0b32cf44")},

    # CONCENTRATE (7)
    {"name": "Shatter 1g", "slug": "shatter-1g", "sku": "CN-SH-1G", "brand": "Glacier Extracts", "category": "concentrate", "sub_category": "Shatter", "strain_type": "sativa", "description": "Glass-like clarity, snappy break.", "price": 18, "is_new": False, "is_featured": False, "package_sizes": ["1g"], "terpenes": ["Pinene", "Limonene", "Caryophyllene"], "effects": ["Energized", "Focused", "Creative", "Uplifted"], "flavor_notes": ["Pine", "Citrus", "Sharp"], "image_url": img("1580127853849-93e599877df2")},
    {"name": "Live Resin Wax 1g", "slug": "live-resin-wax-1g", "sku": "CN-WAX-1G", "brand": "Glacier Extracts", "category": "concentrate", "sub_category": "Wax", "strain_type": "hybrid", "description": "Scoopable, terp-soaked live resin wax.", "price": 24, "is_new": False, "is_featured": True, "package_sizes": ["1g"], "terpenes": ["Myrcene", "Caryophyllene", "Limonene"], "effects": ["Relaxed", "Euphoric", "Creative", "Social"], "flavor_notes": ["Earthy", "Citrus", "Herbal"], "image_url": img("1596394723803-22ccb tried3d")},
    {"name": "Rosin 1g", "slug": "rosin-1g", "sku": "CN-RSN-1G", "brand": "Glacier Extracts", "category": "concentrate", "sub_category": "Rosin", "strain_type": "indica", "description": "Solventless, heat-pressed perfection.", "price": 30, "is_new": True, "is_featured": False, "package_sizes": ["1g"], "terpenes": ["Myrcene", "Linalool", "Caryophyllene"], "effects": ["Relaxed", "Sleepy", "Calm", "Euphoric"], "flavor_notes": ["Grape", "Lavender", "Dough"], "image_url": img("1587049352846-4a222e3d7d78")},
    {"name": "Batter 1g", "slug": "batter-1g", "sku": "CN-BATTER-1G", "brand": "Glacier Extracts", "category": "concentrate", "sub_category": "Batter", "strain_type": "hybrid", "description": "Whipped to a creamy consistency for effortless loading.", "price": 22, "is_new": False, "is_featured": False, "package_sizes": ["1g"], "terpenes": ["Caryophyllene", "Limonene", "Humulene"], "effects": ["Relaxed", "Social", "Creative", "Uplifted"], "flavor_notes": ["Spice", "Citrus", "Cream"], "image_url": img("1588684332863-c92c5c8e5e47")},
    {"name": "Crumble 1g", "slug": "crumble-1g", "sku": "CN-CRUMB-1G", "brand": "Glacier Extracts", "category": "concentrate", "sub_category": "Crumble", "strain_type": "sativa", "description": "Dry, honeycomb texture that crumbles cleanly.", "price": 20, "is_new": False, "is_featured": False, "package_sizes": ["1g"], "terpenes": ["Terpinolene", "Pinene", "Limonene"], "effects": ["Energized", "Uplifted", "Creative", "Focused"], "flavor_notes": ["Tropical", "Pine", "Sweet"], "image_url": img("1604848698030-c434ba08735e")},
    {"name": "Diamonds & Sauce 1g", "slug": "diamonds-and-sauce-1g", "sku": "CN-DMND-1G", "brand": "Glacier Extracts", "category": "concentrate", "sub_category": "Diamonds", "strain_type": "hybrid", "description": "Crystalline THCa diamonds swimming in golden terpene sauce.", "price": 28, "is_new": True, "is_featured": True, "package_sizes": ["1g"], "terpenes": ["Caryophyllene", "Myrcene", "Limonene"], "effects": ["Euphoric", "Relaxed", "Creative", "Uplifted"], "flavor_notes": ["Fuel", "Citrus", "Sweet"], "image_url": img("1601058191520-7d0ed7d4df28")},
    {"name": "Budder 1g", "slug": "budder-1g", "sku": "CN-BUDDER-1G", "brand": "Glacier Extracts", "category": "concentrate", "sub_category": "Budder", "strain_type": "indica", "description": "Silky, spreadable texture with a deep indica profile.", "price": 25, "is_new": True, "is_featured": False, "package_sizes": ["1g"], "terpenes": ["Myrcene", "Linalool", "Humulene"], "effects": ["Relaxed", "Sleepy", "Calm", "Peaceful"], "flavor_notes": ["Berry", "Lavender", "Earth"], "image_url": img("1597266635581-ec64a3d8b4e2")},

    # EDIBLE (7)
    {"name": "Hybrid Gummies 10pk 100mg", "slug": "hybrid-gummies-10pk-100mg", "sku": "ED-GUM-10PK", "brand": "Northern Lights Co.", "category": "edible", "sub_category": "Gummies", "strain_type": "hybrid", "description": "Ten fruit-forward gummies at 10mg each.", "price": 14, "is_new": False, "is_featured": True, "package_sizes": ["10pk"], "terpenes": ["Myrcene", "Limonene"], "effects": ["Relaxed", "Uplifted", "Social", "Creative"], "flavor_notes": ["Mixed Berry", "Tropical", "Citrus"], "image_url": img("1600359746315-fa3e0a993b9e")},
    {"name": "Dark Chocolate Bar 100mg", "slug": "dark-chocolate-bar-100mg", "sku": "ED-CHOC-BAR", "brand": "Northern Lights Co.", "category": "edible", "sub_category": "Chocolate", "strain_type": "hybrid", "description": "Velvety 72% dark chocolate scored into ten precise squares.", "price": 16, "is_new": True, "is_featured": False, "package_sizes": ["1 bar"], "terpenes": ["Caryophyllene", "Linalool"], "effects": ["Relaxed", "Euphoric", "Calm", "Creative"], "flavor_notes": ["Dark Chocolate", "Cocoa", "Vanilla"], "image_url": img("1587132137570-4fab37876396")},
    {"name": "Peppermint Mints 20ct 100mg", "slug": "peppermint-mints-20ct-100mg", "sku": "ED-MINT-TIN", "brand": "Northern Lights Co.", "category": "edible", "sub_category": "Mints", "strain_type": "sativa", "description": "Pocket-sized discretion. Twenty micro-dosed peppermint mints.", "price": 12, "is_new": False, "is_featured": False, "package_sizes": ["20ct tin"], "terpenes": ["Limonene", "Pinene"], "effects": ["Focused", "Uplifted", "Energized", "Social"], "flavor_notes": ["Peppermint", "Cool", "Fresh"], "image_url": img("1583337130417-c1f3ff14bf73")},
    {"name": "Sativa Gummies 5pk 50mg", "slug": "sativa-gummies-5pk-50mg", "sku": "ED-GUM-5PK", "brand": "Northern Lights Co.", "category": "edible", "sub_category": "Gummies", "strain_type": "sativa", "description": "Five tangy citrus gummies packed with sativa energy.", "price": 10, "is_new": True, "is_featured": False, "package_sizes": ["5pk"], "terpenes": ["Limonene", "Terpinolene"], "effects": ["Energized", "Creative", "Uplifted", "Focused"], "flavor_notes": ["Lemon", "Orange", "Tangy"], "image_url": img("1594995846645-3b713157bd77")},
    {"name": "Indica Caramels 10pk 100mg", "slug": "indica-caramels-10pk-100mg", "sku": "ED-CARA-10PK", "brand": "Northern Lights Co.", "category": "edible", "sub_category": "Caramels", "strain_type": "indica", "description": "Buttery, sea-salted caramels that dissolve slowly.", "price": 15, "is_new": False, "is_featured": True, "package_sizes": ["10pk"], "terpenes": ["Myrcene", "Linalool"], "effects": ["Relaxed", "Sleepy", "Calm", "Peaceful"], "flavor_notes": ["Salted Caramel", "Butter", "Toffee"], "image_url": img("1581441363689-1f3a3bee5e14")},
    {"name": "CBD:THC 1:1 Gummies 10pk", "slug": "cbd-thc-1-1-gummies-10pk", "sku": "ED-CBD-GUM", "brand": "Northern Lights Co.", "category": "edible", "sub_category": "Gummies", "strain_type": "balanced", "description": "Equal parts CBD and THC for a gentle, grounded experience.", "price": 18, "is_new": True, "is_featured": False, "package_sizes": ["10pk"], "terpenes": ["Myrcene", "Caryophyllene", "Linalool"], "effects": ["Calm", "Relaxed", "Focused", "Balanced"], "flavor_notes": ["Strawberry", "Peach", "Mango"], "image_url": img("1590318015926-c8404f433bca")},
    {"name": "Honey Sticks Variety 5pk 50mg", "slug": "honey-sticks-variety-5pk-50mg", "sku": "ED-HONEY-STK", "brand": "Northern Lights Co.", "category": "edible", "sub_category": "Honey", "strain_type": "hybrid", "description": "Squeeze into tea, drizzle on toast, or enjoy straight from the stick.", "price": 11, "is_new": False, "is_featured": False, "package_sizes": ["5pk"], "terpenes": ["Myrcene", "Linalool"], "effects": ["Relaxed", "Social", "Creative", "Calm"], "flavor_notes": ["Wildflower Honey", "Floral", "Warm"], "image_url": img("1587049633312-d7e4e4e36c48")},

    # BEVERAGE (7)
    {"name": "Sparkling Lemonade 4pk 40mg", "slug": "sparkling-lemonade-4pk-40mg", "sku": "BV-SPK-4PK", "brand": "Northern Lights Co.", "category": "beverage", "sub_category": "Sparkling", "strain_type": "sativa", "description": "Bright, fizzy lemonade with a 10mg sativa kick per can.", "price": 6, "is_new": False, "is_featured": True, "package_sizes": ["4 x 12oz"], "terpenes": ["Limonene", "Terpinolene"], "effects": ["Uplifted", "Social", "Energized", "Creative"], "flavor_notes": ["Lemon", "Sparkling", "Tart"], "image_url": img("1595981267476-4fa37f1c0ef7")},
    {"name": "Herbal CBD Tea 6pk", "slug": "herbal-cbd-tea-6pk", "sku": "BV-TEA-6PK", "brand": "Northern Lights Co.", "category": "beverage", "sub_category": "Tea", "strain_type": "cbd", "description": "Chamomile and lavender steeped with broad-spectrum CBD.", "price": 8, "is_new": True, "is_featured": False, "package_sizes": ["6 sachets"], "terpenes": ["Linalool", "Myrcene"], "effects": ["Calm", "Relaxed", "Peaceful", "Focused"], "flavor_notes": ["Chamomile", "Lavender", "Honey"], "image_url": img("1597481485289-5f2ea690d041")},
    {"name": "Lemon Sparkling Water 10mg", "slug": "lemon-sparkling-water-10mg", "sku": "BV-LEMON-CAN", "brand": "Northern Lights Co.", "category": "beverage", "sub_category": "Sparkling Water", "strain_type": "hybrid", "description": "Zero sugar, zero calories, all vibes.", "price": 4, "is_new": False, "is_featured": False, "package_sizes": ["12oz can"], "terpenes": ["Limonene", "Pinene"], "effects": ["Relaxed", "Social", "Uplifted", "Calm"], "flavor_notes": ["Lemon", "Clean", "Crisp"], "image_url": img("1598614187854-26a60e1d3ea2")},
    {"name": "Cannabis Cold Brew 12oz 20mg", "slug": "cannabis-cold-brew-12oz-20mg", "sku": "BV-COLD-BREW", "brand": "Northern Lights Co.", "category": "beverage", "sub_category": "Coffee", "strain_type": "sativa", "description": "Colombian single-origin cold brew meets 20mg sativa nano-emulsion.", "price": 7, "is_new": True, "is_featured": True, "package_sizes": ["12oz bottle"], "terpenes": ["Limonene", "Pinene", "Caryophyllene"], "effects": ["Focused", "Energized", "Creative", "Uplifted"], "flavor_notes": ["Coffee", "Chocolate", "Smooth"], "image_url": img("1592663529666-0b5e3b3e79d8")},
    {"name": "Craft Cannabis Soda 4pk 40mg", "slug": "craft-cannabis-soda-4pk-40mg", "sku": "BV-SODA-4PK", "brand": "Northern Lights Co.", "category": "beverage", "sub_category": "Soda", "strain_type": "hybrid", "description": "Small-batch craft sodas in rotating seasonal flavors.", "price": 9, "is_new": False, "is_featured": False, "package_sizes": ["4 x 12oz"], "terpenes": ["Myrcene", "Limonene"], "effects": ["Social", "Uplifted", "Relaxed", "Creative"], "flavor_notes": ["Cola", "Ginger", "Vanilla"], "image_url": img("1589802829990-0bff47fa18e5")},
    {"name": "Cannabis Kombucha 12oz 10mg", "slug": "cannabis-kombucha-12oz-10mg", "sku": "BV-KOMBUCHA", "brand": "Northern Lights Co.", "category": "beverage", "sub_category": "Kombucha", "strain_type": "hybrid", "description": "Tangy, probiotic-rich kombucha with a micro-dose cannabis twist.", "price": 6, "is_new": False, "is_featured": False, "package_sizes": ["12oz bottle"], "terpenes": ["Myrcene", "Caryophyllene"], "effects": ["Calm", "Social", "Uplifted", "Relaxed"], "flavor_notes": ["Ginger", "Green Apple", "Tart"], "image_url": img("1595348020743-4fa37f1c0ef8")},
    {"name": "Herbal Elixir 2oz 25mg", "slug": "herbal-elixir-2oz-25mg", "sku": "BV-ELIXIR", "brand": "Northern Lights Co.", "category": "beverage", "sub_category": "Elixir", "strain_type": "indica", "description": "A concentrated botanical shot with elderberry, turmeric, and 25mg indica nano-emulsion.", "price": 8, "is_new": True, "is_featured": False, "package_sizes": ["2oz bottle"], "terpenes": ["Myrcene", "Linalool", "Caryophyllene"], "effects": ["Relaxed", "Sleepy", "Calm", "Peaceful"], "flavor_notes": ["Elderberry", "Turmeric", "Ginger"], "image_url": img("1600585152220-90363fe70888")},
]


def seed_strains():
    print(f"Seeding {len(STRAINS)} strains...")
    for strain in STRAINS:
        try:
            supabase.table("strains").upsert(strain, on_conflict="slug").execute()
            print(f"  + {strain['name']}")
        except Exception as e:
            print(f"  ! {strain['name']}: {e}")


def seed_products():
    print(f"Seeding {len(PRODUCTS)} products...")
    for product in PRODUCTS:
        try:
            supabase.table("products").upsert(product, on_conflict="sku").execute()
            print(f"  + {product['name']}")
        except Exception as e:
            print(f"  ! {product['name']}: {e}")


if __name__ == "__main__":
    print("Frost Seed Script")
    print("=" * 50)
    seed_strains()
    print()
    seed_products()
    print()
    print("Done!")
